### ISSUE TITLE
Can't integrate Office Update.

### ISSUE THREAD

**Issue by dhnguyen92** [MagerValp/AutoDMG#102]
I want to integrate Office 14.4.7 to my OS X 10.10.2 image, but the output file only has 14.3.0.

By looking at the log, I see lots of error by Office's post install. Most of them are not found error with path 
"/Applications/Microsoft Office 2011/..."

How can I integrate Office update to non-root AutoDMG?

**Comment by jazzace** [comment]
On Jan 28, 2015, at 11:03 AM, Dinh Hai Nguyen <notifications@github.com> wrote:

> I want to integrate Office 14.4.7 to my OS X 10.10.2 image


Unfortunately, it's not gonna happen with Microsoft's installers. Unless you want to go down the road of repackaging with a tool like Composer, you should choose a different way to deploy Microsoft Office. For example, I choose to have DeployStudio install Microsoft's Office installer on first boot of the Mac being (re-)deployed. If I don't have access to the current MS installer, I have it install the original installer and then the updater in sequence. Office does not get installed into my AutoDMG-created image.

(You may find some scripts online that try to patch Microsoft's installers to work with modular image creation tools like AutoDMG, but they have not been maintained and should be considered no longer usable.)

Anthony Reimer
University of Calgary=

**Comment by dhnguyen92** [comment]
Thank you!
