### ISSUE TITLE
Uncaught exception when attempting to write log without perms

### ISSUE THREAD

**Issue by arubdesu** [MagerValp/AutoDMG#103]
I did this to myself, but...
```
abanks$ /Applications/AutoDMG.app/Contents/MacOS/AutoDMG --logfile /var/log/AutoDMG.log build /Users/abanks/Desktop/build/AutoDMG-myAwesomeImage.adtmpl
2015-01-28 14:50:43.839 AutoDMG[12778:607182] AutoDMG died with an uncaught exception, Traceback (most recent call last):
  File "/Applications/AutoDMG.app/Contents/Resources/main.py", line 196, in main
    return cli_main(decoded_argv)
  File "/Applications/AutoDMG.app/Contents/Resources/main.py", line 136, in cli_main
    IEDLog.IEDLogFileHandle = open(logFile, u"a", buffering=1)
IOError: [Errno 13] Permission denied: u'/var/log/AutoDMG.log'
```
I must have written with sudo in the past, but it would be nice to catch the error as I now build as a standard user that's included in sudoers. 
[Line 136](https://github.com/MagerValp/AutoDMG/blob/master/AutoDMG/main.py#L136) is already in a try/except block, not sure how best to break that out to allow for a more graceful/obvious error message.

**Comment by MagerValp** [comment]
Catching (IOError, OSError) fixes it and prints out a nicer error message:

    AutoDMG.app/Contents/MacOS/AutoDMG --logfile /var/log/foo list 10.10.2 14C109
    Couldn't open /var/log/foo for writing

Thanks!
