### ISSUE TITLE
.pkg not running in basic image

### ISSUE THREAD

**Issue by rkivowitz** [MagerValp/AutoDMG#105]
I created a .pkg which runs a script containing three commands. When I put the package into the image, it doesn't run. But if I manually install the same package after a computer has been imaged, it runs without any issue. Any ideas on what might be causing the issue? Is the "Additional Software" section ordered in any way?

The script only enables the Firewall, SSH, and Remote Management. I've copied/pasted it below.

 #!/bin/bash
 
# Enable Firewall
/usr/bin/defaults write /Library/Preferences/com.apple.alf globalstate -int 1
 
# Enable SSH
/usr/sbin/systemsetup -f -setremotelogin on
 
# Enable ARD 
/System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -users namelytech -privs -all -restart -agent

Any ideas? Thanks for your help!

**Comment by arubdesu** [comment]
Hey there, that package has to run from a booted volume. 
Please see [the wiki](https://github.com/MagerValp/AutoDMG/wiki/Packages-Suitable-for-Deployment) for clarification.

**Comment by rkivowitz** [comment]
Ah, ok. That makes sense. Are you aware of any way to have something like this run successfully without having to install it after the machine is booted up?

**Comment by arubdesu** [comment]
Put it in [outset](https://github.com/chilcote/outset), I used to setup launchd's for firstboot with [theLuggage](https://github.com/unixorn/luggage-examples/tree/master/firstboot) but outset makes it a lot easier/standard.

**Comment by arubdesu** [comment]
Or, if you use DeployStudio to restore the image it can deliver the package to run on first boot...

**Comment by jazzace** [comment]
On Mar 4, 2015, at 9:25 AM, rkivowitz <notifications@github.com> wrote:

> Are you aware of any way to have something like this run successfully without having to install it after the machine is booted up?


It does need to be run on first boot, but it can be automated. In my workflow, I use DeployStudio to install such packages (or run such scripts) on first boot. You could also try Joseph Chilcote's Outset (https://github.com/chilcote/outset).


Anthony Reimer
University of Calgary

**Comment by MagerValp** [comment]
Thanks everyone!
