### ISSUE TITLE
-allowUntrusted

### ISSUE THREAD

**Issue by cgerke** [MagerValp/AutoDMG#106]
What are you thoughts on adding this switch to the installer command in installesdtodmg.sh script? I have some legacy printer drivers...or is there a better way to do it?

**Comment by arubdesu** [comment]
If the 'legacy' pkg you're referring to is Brother, that's the only one that I wasn't able to fix recently, reminds me I should check again(redownloading addressed canon and on other). I don't see too much of a problem with this, as it's assumed that the admin knows what they're doing, but you could add this functionality for yourself without even forking, right @cgerke?

**Comment by cgerke** [comment]
yeah i did add it myself, just wondering if others are handling it another
way. perhaps a better way. cheers.

**Comment by MagerValp** [comment]
Wouldn't it be better to just strip the certificate from the pkg instead?

**Comment by arubdesu** [comment]
Yeah, I thought about this some more and think it's a good error to surface to users by default. 

However, I did get bit with the previously mentioned Brother pkg by it canceling the run after 5-ish minutes which wasted a bit of time. Could we parlay this into a pre-flight check of certs on pkgs? It seems pretty straightforward to subprocess out to pkgutil...

**Comment by MagerValp** [comment]
Patches are welcome, but I suspect that it would take a lot more than 5 minutes to implement and test.

**Comment by cgerke** [comment]
I'll strip it, much simpler, maybe an AutoPKG recipe.
