### ISSUE TITLE
Building DMG with iTunes update breaks iTunes installed on /

### ISSUE THREAD

**Issue by antifuchs** [MagerValp/AutoDMG#107]
I just observed this happening while building a blank image with the 10.10.2-14C109 installer (on today's fully-patched Yosemite install, 10.10.2), installing the iTunes 12.1 and Remote Desktop Client 3.8.2 (v1.1) update. After the DMG build ran to completion, starting iTunes on the machine that built the DMG causes iTunes to crash (without a message in Console that I could find).

Reinstalling iTunes from the download at [apple.com](http://www.apple.com/itunes/download/) fixes the crash problem, but it seems like that shouldn't happen (:

Hope this helps track down (or at least repro!) the bug. I'm happy to build more images & try to figure out what files get clobbered, if you need any more details.

**Comment by MagerValp** [comment]
It does log a line, but it isn't particularly helpful:

    2015-03-19 10:18:10,141 com.apple.xpc.launchd[1]: (com.apple.iTunes.80972[37864]) Service exited with abnormal code: 1

The offending script is most likely iTunesX.pkg/preinstall_actions/CleanLocs, which contains the following gem:

    /bin/rm -rf /Applications/iTunes.app/Contents/Resources/*.lproj 2> /dev/null
    /bin/rm -rf /Applications/iTunes.app/Contents/Resources/iTunes.help/Contents/Resources/*.lproj 2> /dev/null

I'm running a build with SIU now, as Apple accepts bug reports for that.

**Comment by MagerValp** [comment]
Confirmed that it breaks in System Image Utility too, as expected. Radar filed (rdar://20221125): http://openradar.appspot.com/radar?id=6190720561971200

**Comment by MagerValp** [comment]
This is no longer an issue with iTunes 12.1.2.
