### ISSUE TITLE
Interesting Image Login Issue

### ISSUE THREAD

**Issue by vincentw8460** [MagerValp/AutoDMG#108]
I've found an interesting issue when building Yosemite with AutoDMG on a VMware VM.

I'm using a Yosemite installation on a VMware VM to build a clean image with only Apple updates and no 3rd party packages.

I'm using Deploy Studio to deploy the image onto a VM for testing and this is what happens when the imaging task is done. The imaging is successful, but instead of presenting the standard OS X new machine setup, I get this. There are no user accounts, so I can't actually log in.

![osx-test](https://cloud.githubusercontent.com/assets/6693452/6767734/fd056616-d010-11e4-8b39-eeefea51928b.png)

**Comment by erikng** [comment]
Are you sure you aren't skipping the Apple Assistant in Deploystudio?

**Comment by vincentw8460** [comment]
Ah yes, sorry my fault. Non issue. I had copied my workflows over from an older machine for an upgrade to Yosemite. They had the skip option set.

**Comment by arubdesu** [comment]
Also, keep in mind it's a lot faster to just convert the asr image into a vm with a tool like @chilcote's [vfuse](https://github.com/chilcote/vfuse)
