### ISSUE TITLE
Error 105

### ISSUE THREAD

**Issue by MScottBlake** [MagerValp/AutoDMG#109]
When using an AD bound mac and the domain is unreachable, the [`chown` command](https://github.com/MagerValp/AutoDMG/blob/58025d126b0fb817645c35dae677d4bff075820c/AutoDMG/installesdtodmg.sh#L202) can fail. In my case, the group was considered to be invalid.

I tested this in a separate bash script and saw the same result using the `chown` command. Using `gid` instead of the group name should fix the problem.

**Comment by MagerValp** [comment]
Please try [1.5.3b388](https://www.dropbox.com/s/dhh2veiik2f58pi/AutoDMG-1.5.3b388.dmg).

**Comment by MScottBlake** [comment]
That build works.

**Comment by MagerValp** [comment]
Excellent.
