### ISSUE TITLE
10.10.2 dmg fails on New macbook air

### ISSUE THREAD

**Issue by killahquam** [MagerValp/AutoDMG#110]
I try creating a dmg from autodmg, and it ouputed a .dmg instead of the .hfs.dmg.
When the restore is complete, the mac doesn't boot

**Comment by erikng** [comment]
The new MacBook Air uses a formed build of 10.10.2. Did you use the one from the Mac App Store because it won't work.

**Comment by killahquam** [comment]
Yeah, I did. building a new build from the mac itself.
Will report back.

**Comment by erikng** [comment]
I hate typos. I meant FORKED but my phone auto corrected. My apologies.
