### ISSUE TITLE
Keyboard Shortcut for "Build"

### ISSUE THREAD

**Issue by zuhl** [MagerValp/AutoDMG#111]
Would it be possible to add a keyboard shortcut (thinking "Command + B") to start the Build process?

I've cloned the code and will try to add via a pull request, but I probably won't be able to get to something like this for a week or so.

Not remotely a critical issue, of course!

Thanks!

**Comment by MagerValp** [comment]
Go for it, sounds like a good idea.

**Comment by zuhl** [comment]
Finally got around to doing this and submitted a [pull request](https://github.com/MagerValp/AutoDMG/pull/112). :-]

**Comment by MagerValp** [comment]
Merged, closing.
