### ISSUE TITLE
Documentation Issue: Running CLI while GUI user is not admin

### ISSUE THREAD

**Issue by jazzace** [MagerValp/AutoDMG#114]
Unexpected behaviour I found:
While logged in as a Standard User in the GUI, I opened Terminal and proceeded to start a shell session in an admin account (because I knew I would need SuperUser powers for AutoDMG to run at the command line). I then asked AutoDMG to run via the command line using a template. It read the template successfully and then attempted to start the installation. It failed as follows:

```
Starting phase: Starting install
phase: Starting install
Install task running
May 22 16:08:24 JazzaceMac.local AutoDMG[94329] <Error>: Set a breakpoint at CGSLogError to catch errors as they are logged.
May 22 16:08:24 JazzaceMac.local AutoDMG[94329] <Error>: This user is not allowed access to the window system right now.
_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
Workflow failed: Build failed (Application isn’t running.)
Build failed: Build failed
    Application isn’t running.
```

Unless there is an easy fix, I'd suggest changing the documentation to state that that command line users must also be logged in to the GUI of the same (admin) account before proceeding (in the same way that it is a requirement that you be booted into the same major version of the OS for which you want to create an image).

**Comment by MagerValp** [comment]
Could you try [AutoDMG-1.6.1b457](https://www.dropbox.com/s/97d9r2tdbuxmnxt/AutoDMG-1.6.1b457.dmg) and see if this issue has been resolved?

**Comment by n8felton** [comment]
FWIW, I had the same issue and 1.6.1b457 fixed it for me.
