### ISSUE TITLE
AutoDMG build: error: too few arguments

### ISSUE THREAD

**Issue by vincentw8460** [MagerValp/AutoDMG#115]
I'm new to the CLI aspect of AutoDMG, so bear with me if I'm missing something simple. Whenever I run the following command, I get this error:

```
vincentw@vincentw3maclap:[~]: /Applications/AutoDMG.app/Contents/MacOS/AutoDMG --log-level 7 --logfile /Users/vincentw/Desktop/auto-build.log build --download-updates --installer /Applications/Install\ OS\ X\ Yosemite.app
usage: AutoDMG build [-h] [-o OUTPUT] [-i INSTALLER] [-n NAME] [-u] [-U] [-f]
                     source [packages [packages ...]]
AutoDMG build: error: too few arguments
vincentw@vincentw3maclap:[~]: 
```

I'm not providing any specific template, I just want to try to make a base install with the newest updates for Yosemite.

**Comment by arubdesu** [comment]
Looks like, from the wiki page, that you only use an `installer` flag to override one that would be set in a template, so put the path to the installer just after the build arg instead

**Comment by vincentw8460** [comment]
I think that was it. I also needed an output path, which I was missing before. 

My final command ended up being:

```
/Applications/AutoDMG.app/Contents/MacOS/AutoDMG --log-level 7 --logfile /Users/vincentw/Desktop/auto-build.log build /Applications/Install\ OS\ X\ Yosemite.app --download-updates --output /Users/vincentw/Desktop/Yosemite-Auto-Build.dmg
```
