### ISSUE TITLE
.DS_Store in root of DMG

### ISSUE THREAD

**Issue by erikng** [MagerValp/AutoDMG#116]
I noticed a .DS_Store is located in the root. Macintosh HD/.DS_Store

**Comment by MagerValp** [comment]
So does every system drive I have. Is an image created with SIU different?

**Comment by erikng** [comment]
Haven't tested with SIU but I noticed it when comparing it to an old DMG today. It didn't have a DS store file.

**Comment by MagerValp** [comment]
I don't have any images older than 10.8.5 lying around, but mine all have one. Unless there's a compelling reason to remove them I think I'll just leave them be.

**Comment by erikng** [comment]
Didn't expect that but okay.
