### ISSUE TITLE
Admin Option - Do not create /private/var/log/AutoDMG-DATE.adtmpl file

### ISSUE THREAD

**Issue by erikng** [MagerValp/AutoDMG#117]
In doing my own security audits, I noticed that my hidden service account is not truly hidden.

This is for several reasons including but not limited to:
1. I have a verbose script in DeployStudio that mentions said account (now resolved)
2. adtmpl file references package location and name.
3. Package Name / Receipt left on machine also mentions account

While obviously I can't hide every single reference, I would like an option to not generate this log.

**Comment by MagerValp** [comment]
Unless we go into rootkit territory, "hidden" accounts aren't really hidden, they're just not displayed in the GUI for users. Anyone who knows to dig around in /var/log or package receipts would probably start by looking in dscl or /private/var/db/dslocal where you'll never be able to hide it. You also have the cfprefsd and distnoted processes running for all local accounts even when not logged in.

Removing the adtmpl breaks using a previous image as a source, and I'm reluctant to add an option that's likely to shoot people in the foot. You can always remove the adtmpl with srm in a script after laying down the image.

**Comment by erikng** [comment]
Fair enough. I'm doing that now. Is it not possible to look for this template outside of the dmg though?

**Comment by MagerValp** [comment]
No, the idea is that the adtmpl inside is what was used to build the image, since there's no easy way to infer e.g. if updates have been applied.
