### ISSUE TITLE
AutoDMG fails to accept OSX image

### ISSUE THREAD

**Issue by streetscholar** [MagerValp/AutoDMG#118]
HI, I am a Mac novice, I am trying to use AutoDMG, when I drag and drop the OSXupd 10.10.3 into AutoDMG it says "Invalid Source, couldnt find system version" please could someone tell me what I am doing wrong? Thanks.

**Comment by MagerValp** [comment]
That sounds like an OS update and not an OS installer. Use an installer downloaded from the App Store, as described in [Getting Started](https://github.com/MagerValp/AutoDMG/wiki/Getting-Started).

**Comment by streetscholar** [comment]
Dear Prof,
Sorry ot be a pain but could you tell me where  Ican download the installer from? I have searched online and am only getting the update

Thanks.

Date: Tue, 21 Jul 2015 02:41:09 -0700

**Comment by arubdesu** [comment]
@streetscholar the Mac App Store, as it has been available through since 10.7.

**Comment by streetscholar** [comment]
Thanks buddy. I am an IT professional but have had very limited exposure to OSX, have been handed control of a Mac suite so am having to learn fast! Thanks again.
