### ISSUE TITLE
Enhancement: resizing for top (update) and bottom (additional software panes)

### ISSUE THREAD

**Issue by rmanly** [MagerValp/AutoDMG#119]
It would be nice to make the horizontal bar (red arrow in pic) movable up & down along the green arrows so that more content can be displayed in either the top or bottom portion as needed.

[screen_shot_2015-08-04_at_7_56_39_am](https://cloud.githubusercontent.com/assets/1110967/9061078/d891e290-3a7e-11e5-99df-be2852bda339.jpg)

**Comment by erikng** [comment]
Devils advocate but why are you adding all of those packages in the first place?

**Comment by rmanly** [comment]
because deploying with a thunderbolt cable takes 1 minute and munki would take a LOT longer.

**Comment by MagerValp** [comment]
Finally added in the upcoming 1.7.1!

**Comment by rmanly** [comment]
Cool!
