### ISSUE TITLE
JDK 8 Update 51.pkg fails with AutoDMG v1.5.3

### ISSUE THREAD

**Issue by daroloson** [MagerValp/AutoDMG#121]
Yosemite 10.10.5 Installer version 1.6.43 (14F27)

JDK 8 Update 51.pkg

Build failed
JDK 8 Update 51.pkg failed with return code 1

Installs manually or through ARD fine.

2015-08-18 10:54:41 Info: AutoDMG v1.5.3 build 393
2015-08-18 10:54:41 Info: Mac OS X 10.10.3 14D136
2015-08-18 10:54:41 Info: CPython 2.7.6 (GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39))
2015-08-18 10:54:41 Info: PyObjC 2.5.1

Current workaround is staying with jdk-8u45.pkg which works fine.

**Comment by arubdesu** [comment]
Hey @daroloson, could you please confirm you've reviewed https://github.com/MagerValp/AutoDMG/wiki/Packages-Suitable-for-Deployment ? As you may know, just because it works in Apple Remote Desktop or manually doesn't mean it will work in AutoDMG. Thanks

**Comment by MagerValp** [comment]
The preinstall and postinstall scripts in the JDK packages blatantly disregard $3 and won't work when building an image. You'll have to repackage or file a bug with Oracle.
