### ISSUE TITLE
El Capitan 10.11.1 Profile?

### ISSUE THREAD

**Issue by shieldsem81** [MagerValp/AutoDMG#126]
I'm fairly new to AutoDMG and am very impressed by this amazing little app. I'm wondering when at 10.11.1 profile will be available?

I ask because the new installer is throwing an error when I attempt to use autodmg.

**Comment by arubdesu** [comment]
Hey there, @MagerValp is already on it. https://github.com/MagerValp/AutoDMGUpdateProfiles/commit/27ac592717985826a8972422c24a66680216f51b
Command-U, or it'll look for new profiles on launch.
