### ISSUE TITLE
Disk space only calculates space on OS volume, & not volume selected to use for OS.dmg

### ISSUE THREAD

**Issue by macmule** [MagerValp/AutoDMG#128]
I pointed AutoDMG to a second HD to create the OS.dmg within, however AutoDMG kept advising that I did not have enough free space (15GB).

The destination volume have 25GB free, but the OS volume had 13.5GB.

**Comment by jazzace** [comment]
The essential bit of code, from lines 86-93 of installesdtodmg.sh is:

````
# Get a work directory and check free space.
tempdir=$(mktemp -d -t installesdtodmg)
tempdirs+=("$tempdir")
freespace=$(df -g "$tempdir" | tail -1 | awk '{print $4}')
if [[ "$freespace" -lt 15 ]]; then
    echo "IED:FAILURE:Less than 15 GB free disk space, aborting"
    exit 100
fi
````

Is it possible that the tempdir is on the boot drive but the compressed image goes to wherever --output (or the template) suggests? That is, the error message is accurate but the tempdir is not where you expect it to be. (I can't read shell script & Python well enough to tell.) Just trying to more clearly define the problem.

**Comment by macmule** [comment]
Yep I think that's the issue. 

I'd suggest that the temp dir be created on the same volume as selected for the OS.dmg.  

Regards,

Ben.

**Comment by MagerValp** [comment]
AutoDMG respects the `$TMPDIR` shell variable, you can point it to another volume if you don't want to use /var/folders. Trying to guess where to create the temp directory is far too error prone.

**Comment by erikberglund** [comment]
Maybe a solution that's both easy to implement and could help in these cases is to make the temporary directory a setting? Either default ($TMPDIR) or user selected?

**Comment by MagerValp** [comment]
@macmule is this GUI or commandline? Building in a VM?

**Comment by macmule** [comment]
GUI. 

Just dropped the "Install OS X app" in & selected the 100GB second disk as output location.

**Comment by MagerValp** [comment]
@erikberglund it's one of those things that *should* be easy to fix, but due to the program's architecture it's not as straightforward as I'd like. Ideally it should just be a warning and not an error, but I have no way of interacting with the user in the build script.
