### ISSUE TITLE
Security Update 2015-007 changes Yosemite build to 14S1021

### ISSUE THREAD

**Issue by erikng** [MagerValp/AutoDMG#129]
After applying Security Update 2015-007 to a Yosemite 10.10.5 AutoDMG, the sub build is changed to 14S1021. Subsequent changes to this DMG will result in AutoDMG throwing up a warning for "unknown build".

**Comment by MagerValp** [comment]
I had some thoughts on making certain builds equivalent, but for now we'll just mask this warning by adding empty entries to UpdateProfiles.
