### ISSUE TITLE
Safari 9.0.1 Yosemite

### ISSUE THREAD

**Issue by scifiman** [MagerValp/AutoDMG#130]
I'm getting an error for the Safari 9.0.1 Yosemite update.
The download fails the SHA1 checksum expectation.  AutoDMG expected:
8a15d48c94d7b04f89cb3b3faff0dfcc8f7c1859
but got:
abad1886301a442e850b3bf203007b08a7bff5e2

This is happening on a 10.10.5 VM.  I've also had issues with this update on my 10.10.5 desktop where it will not install from the AppStore.  So I wonder if something has changed with this file from Apple.

**Comment by MagerValp** [comment]
Apple might have updated the build, we got the patch twice in AM too, I'll investigate. Moved the issue over here: https://github.com/MagerValp/AutoDMGUpdateProfiles/issues/25
