### ISSUE TITLE
Unexpectedly quit

### ISSUE THREAD

**Issue by ktappe** [MagerValp/AutoDMG#132]
At the end of the build as AutoDMG was scanning the image for restore (2nd pass), it quit. Here is the crash log: [AutoDMG-crash.txt](https://github.com/MagerValp/AutoDMG/files/34577/AutoDMG-crash.txt)

**Comment by ktappe** [comment]
Did not happen the next time I ran "AutoDMG build"...

**Comment by MagerValp** [comment]
Wow, that's a hard crash in the python interpreter. Nothing I can debug or fix I'm afraid, but please post if it shows up again. Marking it as `wontfix` for now.
