### ISSUE TITLE
Task exited with status 1

### ISSUE THREAD

**Issue by rankle07** [MagerValp/AutoDMG#133]
Hi,

I have been trying to make an image with el capitan. 

But overtime i try and create one, i get the error 'task exited with status 1. 

I have tried with and without adding any extra apps to push.

help would be greatly appreciated.

Thanks 

[AutoDMG 2015-11-17 16.17.pdf](https://github.com/MagerValp/AutoDMG/files/36917/AutoDMG.2015-11-17.16.17.pdf)

**Comment by MagerValp** [comment]
The image scanning fails for some reason. You can look in the system.log between 2015-11-17 16:17:06 and 2015-11-17 16:17:08 to see if there are any error messages.

You can also try running asr manually and see what the error is: `asr imagescan --source /Users/nbruce/Desktop/osx_updated_151022-10.11.1-15B42.hfs.dmg`

**Comment by rankle07** [comment]
Hi,

Thank you for your speedy reply. I mistakenly deleted the first image file, so i rebooted and tried again. Same error. 

I ran asr manually and below are the results.


nbruce$ asr imagescan --source /Users/nbruce/Desktop/osx_updated_151022-10.11.1-15B42.hfs.dmg
Block checksum: ....10....20....30....40....50....60....70....80....90....100
Block checksum: ....10....20....30....40....50....60....70....80....90....100
Block checksum: ....10....20....30....40....50....60....70....80....90....100
successfully scanned image "/Users/nbruce/Desktop/osx_updated_151022-10.11.1-15B42.hfs.dmg"

Thanks

**Comment by MagerValp** [comment]
Well no error there... So what does `system.log` say between the times when AutoDMG fails?

**Comment by rankle07** [comment]
To me it looks like no errors again:

Nov 17 16:16:48 Nicholass-MacBook-Pro com.apple.backupd-helper[967]: Not starting scheduled Time Machine backup: Backup already running
Nov 17 16:17:06 Nicholass-MacBook-Pro AutoDMG[541]: Starting task with 4 phases
Nov 17 16:17:06 Nicholass-MacBook-Pro AutoDMG[541]: Starting phase: Scanning disk image
Nov 17 16:17:06 Nicholass-MacBook-Pro AutoDMG[541]: Finalize task running
Nov 17 16:17:08 Nicholass-MacBook-Pro AutoDMG[541]: Task exited with status 1
Nov 17 16:17:08 Nicholass-MacBook-Pro AutoDMG[541]: Workflow failed: Build failed (Task exited with status 1)
Nov 17 16:17:16 Nicholass-MacBook-Pro com.apple.backupd[970]: Finished scan

**Comment by MagerValp** [comment]
I added a little extra logging, see if this build sheds any light on it: [AutoDMG-1.5.3b409.dmg](https://www.dropbox.com/s/c1339r9pi1o0apy/AutoDMG-1.5.3b409.dmg)

**Comment by rankle07** [comment]
Hi,

Latest attempt with your beta version.

Many thanks for your help so far.

[AutoDMG 2015-11-18 15.45.txt](https://github.com/MagerValp/AutoDMG/files/38017/AutoDMG.2015-11-18.15.45.txt)

**Comment by MagerValp** [comment]
Yes, finally an error message:

```
2015-11-18 15:45:01 Info: Launching finalize with arguments:
2015-11-18 15:45:01 Info:     '/Volumes/AutoDMG-1.5.3b409/AutoDMG.app/Contents/Resources/progresswatcher.py'
2015-11-18 15:45:01 Info:     '--socket'
2015-11-18 15:45:01 Info:     '/tmp/se.gu.it.IEDSocketListener.41c5515c02a42770'
2015-11-18 15:45:01 Info:     'imagescan'
2015-11-18 15:45:01 Info:     '/Users/nbruce/Desktop/osx_updated_151022-10.11.1-15B42.hfs.dmg'
2015-11-18 15:45:03 Info: asr output: can't open "/Users/nbruce/Desktop/osx_updated_151022-10.11.1-15B42.hfs.dmg" read/write
2015-11-18 15:45:03 Info: asr output: asr: image scan failed - Permission denied.
2015-11-18 15:45:03 Error: Task exited with status 1
```
Any idea why it wouldn't be able to read/write to a file that it newly created? What does ls -led /Users/nbruce/Desktop/osx_updated_151022-10.11.1-15B42.hfs.dmg say? Have you tried saving in `~/Downloads` or `/Users/Shared` instead?

**Comment by rankle07** [comment]
Yea i saw the ' can't open ' and thought permissions.

 t-rw-r--r--@ 1 501  staff  8191514184 18 Nov 15:45 /Users/nbruce/Desktop/osx_updated_151022-10.11.1-15B42.hfs.dmg

**Comment by rankle07** [comment]
same issue when trying to save to downloads folder.

I have reset all the permissions for my admin account. Made my user area read and write. Will try again and see how that helps.

**Comment by rankle07** [comment]
even after reseting all the permissions, I'm still getting the same area, tried saving it to share folder as well as downloads.

**Comment by rankle07** [comment]
I have tried on a different user account and it worked fine. 

So it is something on my main account that is causing this. I have tried repairing the permissions via console and it repaired a lot. But the issue still stands. 

When it creates the file it doesn't seem to add any permission for this user. Any clue on how to resolve it?
other than deleting this account and creating a new account?.

thanks

**Comment by MagerValp** [comment]
The fact that it shows the owner as `501` is a pretty clear sign that the permissions on your homedir are wrong. I'm not sure what you mean by reset permissions, but `chown -hR $(id -u):$(id -g) ~` should fix it.

**Comment by rankle07** [comment]
sudo /usr/libexec/repair_packages --repair --standard-pkgs --volume / 

thats the command i used to repair permissions. 

But i have run the command you sent me and I am now giving autoDMG another go.

thanks

**Comment by rankle07** [comment]
Hi,


Still got the same permissions error after running the command you sent.

**Comment by rankle07** [comment]
[AutoDMG 2015-11-20 09.16.txt](https://github.com/MagerValp/AutoDMG/files/39890/AutoDMG.2015-11-20.09.16.txt)

latest error log

**Comment by MagerValp** [comment]
In that case create a new admin account, the one you have is broken.

**Comment by rankle07** [comment]
I thought that might be the case. 

Thank you for all your help.
