### ISSUE TITLE
Task Failed when adding Adobe package

### ISSUE THREAD

**Issue by rankle07** [MagerValp/AutoDMG#134]
Hi,

Every time i try and create an install with the Adobe CC deployment package attached, i get the below error and the task fails to complete.

I have tried creating a fresh package with different apps inside the installer, but it still doesn't work.

Any help would be appreciated.
Many thanks 

[AutoDMG 2015-11-26 14.42.txt](https://github.com/MagerValp/AutoDMG/files/45045/AutoDMG.2015-11-26.14.42.txt)

**Comment by erikng** [comment]
Adobe CC packages are terrible and assume a lot of things about the destination. I would blame Adobe CC and not AutoDMG.

**Comment by MagerValp** [comment]
Adobe CC packages only support being installed on a live system. They violate nearly every rule in [Packages Suitable for Deployment](https://github.com/MagerValp/AutoDMG/wiki/Packages-Suitable-for-Deployment).
