### ISSUE TITLE
Support creating case-sensitive filesystems

### ISSUE THREAD

**Issue by ryandesign** [MagerValp/AutoDMG#138]
AutoDMG appears to always format the disk image with the case-insensitive journaled HFS+ filesystem using `hdiutil create ... -fs HFS+J`. Would there be a way to specify a different disk format? For example, I would like to use the case-sensitive journaled HFS+ filesystem. I realize this is esoteric, and it would be ok if it were only exposed in the template and/or command line, and not an option in the GUI.

**Comment by arubdesu** [comment]
You can (currently) override it here: https://github.com/MagerValp/AutoDMG/blob/master/AutoDMG/installesdtodmg.sh#L101 in your copy of the app, but I think you're going to get a similar response as those who wanted to create images without recovery partitions, like https://github.com/MagerValp/AutoDMG/issues/8

**Comment by MagerValp** [comment]
Allister is right on track. I'm curious as to why you want a case-sensitive OS volume though? The last time I accidentally installed on a case sensitive volume things didn't end well...

**Comment by ryandesign** [comment]
I simply want to use a case-sensitive filesystem for the servers I'm setting up. I can edit the script in the application bundle for now, but that's quite inelegant.

**Comment by MagerValp** [comment]
Right, I can see why you'd have a case sensitive volume for file sharing or web hosting, but the system volume?
