### ISSUE TITLE
TMPDIR; temp directory relocation not working ?

### ISSUE THREAD

**Issue by mark-cohen** [MagerValp/AutoDMG#140]
AutoDMG requires a minimum of 15GB of free space to allow for the required caching of packages. By default this is allocated to the /var/folders directory on the startup volume. Should the required free space not be available in the default location, or should the user wish to direct the caching elsewhere - issuing the following command should redirect AutoDMG's caching (to "/Volumes/Storage/PlentyoRoomHere/" as per the example), but doesnt:
"export TMPDIR=/Volumes/Storage/PlentyoRoomHere/"

You can verify the location of the TMPDIR using the following command: "echo $TMPDIR"

Even once TMPDIR has been redirected, build will fail, and AutoDMG will state: "Error: Workflow failed: Build failed (Less than 15 GB free disk space, aborting)"

Thanks.

**Comment by MagerValp** [comment]
I confirmed that this is a regression in OS X 10.9 and up, it worked on 10.8 and below. I have commited a fix in 1.5.5.
