### ISSUE TITLE
Building El Capitan 10.11.3 Never Finishes

### ISSUE THREAD

**Issue by ktappe** [MagerValp/AutoDMG#143]
I've tried to build 10.11.3 (15D21) four times now, both using CLI and GUI, and it never completes.  One of the instances I let run all weekend (nearly 3 days) and it never progressed. When I give up and hit Control-C, the iMac (Late 2013 with SSD) kernel panics (when exiting the CLI; no kernel panic when exiting the GUI). Log attached.
[AutoDMG 2016-02-01 13.30.txt](https://github.com/MagerValp/AutoDMG/files/112802/AutoDMG.2016-02-01.13.30.txt)

**Comment by ktappe** [comment]
Update: It appears AutoDMG isn't completely dead. An hour later it added two more entries to the log. These:

installd: installd: Starting
installd: installd: uid=0, euid=0

These keep being added to the log, roughly once an hour.

**Comment by MagerValp** [comment]
Since it kernel panics I'm pretty sure your admin machine is hosed somehow. Have you tried building on a clean machine/vm?

**Comment by ktappe** [comment]
My Mac's hard drive was dying, just in a non-obvious way. Please close/disregard this report.

**Comment by ktappe** [comment]
Per your request on twitter, here is a small Composer-generated package that errors out in AutoDMG.  

Hope it helps,
-Kurt

**Comment by ktappe** [comment]
Rebooting the Mac in Safe Boot then rebooting normally allowed AutoDMG to build using this package.

Do you have any ideas why that was necessary?  (A regular reboot did not solve the error.)

My impression is that 10.11.x is a lot less stable than 10.10 was.  What are your experiences?

-Kurt
