### ISSUE TITLE
Feature idea: skipping `asr imagescan`

### ISSUE THREAD

**Issue by timsutton** [MagerValp/AutoDMG#144]
I've been using AutoDMG for some scenarios where I only want to convert the result to a VMDK, and for which the `asr imagescan` step wouldn't be needed. In some cases the output DMG is around ~14GB compressed, so the scan adds a fair amount of time.

What do you think of the idea of adding an option to skip the restore process? I'm not sure there are other "post-processing" modifications that would ever make sense for AutoDMG to do with the resulting DMG, but this has been one I've wanted on a number of occasions. I assume that if you would consider a PR to this effect, would this be something you would want to define in the "Advanced" window so that it could be accessible via the GUI, a template and the CLI `build` command?

**Comment by MagerValp** [comment]
Go for it.

**Comment by timsutton** [comment]
Great! After messing around with the code for a while, here's what I've implemented, very roughly. Let me know if this seems sane, if you have thoughts on how it could be done differently:

* Add a checkbox called "Don't Scan for Restore" in Advanced after the image name and size options, which defaults to off.
* This propagates a boolean value down to the IEDTemplate and IEDWorkflow similarly to how the other Advanced options work.
* The resulting template stores a boolean key `SkipAsrImagescan`
* The actual logic at the time of building is that when the IEDWorkflow's task list is being built, if this attribute is `True`, the [Finalize task](https://github.com/MagerValp/AutoDMG/blob/e8232b6031be64a41eba5741a09f9ef1553deb36/AutoDMG/IEDWorkflow.py#L391-L400) is simply not added. With this, no changes are needed for either of the underlying engine scripts.

No CLI option's been added yet but I'd add something like `--dont-scan-for-restore` (or `--skip-scan-for-restore`) them to the build command.

The terminology used for these options ("Don't", "Skip", "imagescan" etc.) aren't consistent but I chose them to reflect the context (app code, `asr` options and user-facing UI elements) in which they're used.

**Comment by MagerValp** [comment]
:+1:

I'd go with `--skip-asr-imagescan` to match the template bool.

**Comment by timsutton** [comment]
Thanks - I'll open a PR to start posting commits.

**Comment by MagerValp** [comment]
Merged, thanks!
