### ISSUE TITLE
Using a base image as a source via CLI considered invalid

### ISSUE THREAD

**Issue by timsutton** [MagerValp/AutoDMG#147]
If a base image is used as a source in the CLI, `AutoDMG build` returns:

`foo.hfs.dmg is not a valid OS X installer or AutoDMG template`

It works fine if a template is passed via CLI instead, but `IEDCLIController.py` seems to check only for either a .app/ESD or a template file as valid sources.

**Comment by MagerValp** [comment]
Confirmed: in `IEDCLIController.cmdBuild_()` if `IEDUtil.installESDPath_(args.source)` returns `None` it should simply check if the name ends with `.dmg`, and in that case use `IEDUtil.resolvePath_()` to resolve any links or aliases and continue.
