### ISSUE TITLE
How create French Deploy with 10.11 & AutoDMG

### ISSUE THREAD

**Issue by SkaraBee** [MagerValp/AutoDMG#150]
When i create my img for DeployStudio all my dmg (10.11) are deploy in English. How it's possible to change the language to French by default ? 
I choose French at the beginning of installation but the OS stay in English at the first start.

Thanks for support.
Aurélien

**Comment by MagerValp** [comment]
If you use French language when AutoDMG runs then the image it builds will default to French. However, if you use DeployStudio it has its own localization settings that overwrites the image. You have to add a localize step to DeployStudio and configure that.

PS: You might want to check out [MacAdmins on Slack](http://macadmins.org), it's the fastest place for getting help with issues like this.
