### ISSUE TITLE
Temporary files not located in the destination volume

### ISSUE THREAD

**Issue by ygini** [MagerValp/AutoDMG#151]
At this time, AutoDMG require 15 GB free on the startup volume.

Even if I've 500 GB free on another volume used as target for my dmg, AutoDMG still use my boot volume for caching and work in process.

A way to change the working folder is necessary.

**Comment by ygini** [comment]
After reading ```installesdtodmg.sh``` script, I've seen the existence of ```TMPDIR``` environmental variable. 

When using it with command line directly, it works.

So it would be great to have a settings with the GUI version to set it.

**Comment by MagerValp** [comment]
See issue #140: as of 1.5.5 `TMPDIR` works again. To set it for the GUI use `launchctl setenv TMPDIR "/Volumes/Big HD/tmp"` and restart AutoDMG. To permanently set the variable, see [stackoverflow](http://stackoverflow.com/questions/25385934/setting-environment-variables-via-launchd-conf-no-longer-works-in-os-x-yosemite).

**Comment by ygini** [comment]
Yes but no, or find an other name for ```TMPDIR```

I wont change an env var with such a common name for one software…

This kind of settings is specific to a software and should not rely only on env var.

**Comment by MagerValp** [comment]
As it came up in the Slack support today, run the GUI version from the Terminal:

    $ TMPDIR=/path/to/big/drive /Applications/AutoDMG/Contents/MacOS/AutoDMG

This way the TMPDIR is set for AutoDMG, but no other apps.

**Comment by MagerValp** [comment]
I've decided against implementing a UI for this, since this works both for GUI and CLI, and just requires launching from the Terminal. I've added it to [the wiki](/MagerValp/AutoDMG/wiki/FAQ#8-autodmg-complains-that-i-dont-have-enough-space-even-though-im-saving-to-a-large-external-drive).
