### ISSUE TITLE
AutoDMG should not relaunch after a login

### ISSUE THREAD

**Issue by nmcspadden** [MagerValp/AutoDMG#152]
If a machine reboots during AutoDMG building, and app persistence is enabled, AutoDMG relaunches a stuck process on the next login.

This should be disabled.  Greg Neagle suggested code like this, used from Munki:
https://github.com/munki/munki/blob/master/code/apps/Managed%20Software%20Center/Managed%20Software%20Center/MSCAppDelegate.py#L61-L63

```
        # Prevent automatic relaunching at login on Lion+
        if NSApp.respondsToSelector_('disableRelaunchOnLogin'):
            NSApp.disableRelaunchOnLogin()
```

**Comment by MagerValp** [comment]
Thanks, fixed in 1.6.
