### ISSUE TITLE
Download failed - Safari 9.1.2 for Yosemite failed with HTTP 404

### ISSUE THREAD

**Issue by apizz** [MagerValp/AutoDMG#155]
Thinking this is a profile issue for creating a Yosemite OS DMG.  Tried downloading updates to 10.10.5 Yosemite, but fails to download Safari 9.1.2 update.  Checked App Store updates and looks like there is a Safari 9.1.3 update available now.

Thank you for building and maintaining such a killer Mac Admin tool!

**Comment by arubdesu** [comment]
@apizz thanks for reporting this, if you get to it before us please feel free to send a pull request to the [update profiles repo](https://github.com/MagerValp/AutoDMGUpdateProfiles)

**Comment by apizz** [comment]
@arubdesu sadly I am Github nub and have never done a pull request :/.  I tried to run the autodmg-rss.py script to create an updates.plist file but every time it ran it didn't populate the plist with any info.  I also looked at the UpdateProfiles.plist but couldn't seem to figure out how to discern the full http://swcdn.apple.com/content/downloads/... path to the update. 

Checked the RSS feed to and it doesn't appear the 9.1.3 Safari update made it's way to the feed for whatever reason.

I was able to get this working for me by downloading the Safari 9.1.3 update PKG manually using a `sudo softwareupdate -l -a` and then `sudo softwareupdate --download name_of_update` so I could drag the PKG from /Library/Updates into the additional software section of AutoDMG.

**Comment by MagerValp** [comment]
Thanks for the heads up, I've added Safari 9.1.3 to the profiles.

Annoyingly Apple doesn't post Safari updates to the rss feed. You have to use the `sucatalog.sh` script to grab the Software Update catalogs, and search for them in there:

    $ ./sucatalog.sh
    $ egrep -i 'safari.*\.pkg' *.sucatalog | cut -d\> -f2-| cut -d\< -f1 | sort -u 
    http://swcdn.apple.com/content/downloads/17/39/031-72723/qjk9m4oqqk3jn16o5w4gupeta7uqek1lhi/Safari10.0YosemiteSeed.pkg
    http://swcdn.apple.com/content/downloads/18/14/091-9898/opy4mtpobcg21e1xj2l0uy9ayvq2ys59zs/Safari5.1.10SnowLeopard.pkg
    http://swcdn.apple.com/content/downloads/43/04/031-05867/xcrpn0l2nziw9mglb0gksv2rndu0nquggd/Safari6.1.6Lion.pkg
    http://swcdn.apple.com/content/downloads/45/36/031-28342/piu9tsargpvuaxdnlhf1s0dulnxiuxc8ee/Safari6.2.8MountainLion.pkg
    http://swcdn.apple.com/content/downloads/47/05/031-75479/smgdhqybff3jofycbq8uuciu5td7co45am/Safari9.1.3Mavericks.pkg
    http://swcdn.apple.com/content/downloads/50/48/031-74172/ysyvw0y92rsipxbxb4yxyw5mo2fqc9hcmq/SafariTechPreviewElCapitan.pkg
    http://swcdn.apple.com/content/downloads/62/05/031-75481/c10gu5qoz8bbbk1jczzzvxm9ih4fupo0wz/Safari9.1.3Yosemite.pkg
