### ISSUE TITLE
Software updates not updating

### ISSUE THREAD

**Issue by ChicagoJay** [MagerValp/AutoDMG#156]
I've been using AutoDMG ever since we started using Casper, in the spring of 2015.  Fantastic product - thank you!

Everything in 1.5.5 is working fine for us, but I have a question.  Is there a cache we can clear, to make it search for updates again?  Our AutoDMG is still seeing the Digital Camera RAW update 6.20, when 6.21 has been released.  Also, it's seeing iTunes 12.4.3, when the current version is 12.5.1.

This integration of updates with the base installer image is a tremendously useful feature, and my colleagues and I would love to see it working perfectly!

Thanks again!

--
Jay Duff, ACMT, CCT
Mannheim School District 83
Franklin Park, IL

**Comment by MagerValp** [comment]
Updates are added manually in the https://github.com/MagerValp/AutoDMGUpdateProfiles repo. Selecting Update Profiles… in the menu brings in the latest ones (and AutoDMG does it automatically once per day or so). iTunes should be current now, but I haven't had a chance to verify Camera RAW yet.

**Comment by ChicagoJay** [comment]
Thank you for the explanation.
    
    Now you can add Safari 10 to the list!  (Thanks, Apple)....
    --
Jay Duff, ACMT, CCT
Network Specialist
Mannheim School District 83
Franklin Park, IL
    On 9/20/2016 1:31 PM, Per Olofsson
      wrote:
    
    
      Updates are added manually in the https://github.com/MagerValp/AutoDMGUpdateProfiles
        repo. Selecting Update Profiles… in the menu brings in the
        latest ones (and AutoDMG does it automatically once per day or
        so). iTunes should be current now, but I haven't had a chance to
        verify Camera RAW yet.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MagerValp/AutoDMG","title":"MagerValp/AutoDMG","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/MagerValp/AutoDMG"}},"updates":{"snippets":[{"icon":"PERSON","message":"@MagerValp in #156: Updates are added manually in the https://github.com/MagerValp/AutoDMGUpdateProfiles repo. Selecting Update Profiles… in the menu brings in the latest ones (and AutoDMG does it automatically once per day or so). iTunes should be current now, but I haven't had a chance to verify Camera RAW yet."}],"action":{"name":"View Issue","url":"https://github.com/MagerValp/AutoDMG/issues/156#issuecomment-248390551"}}}
