### ISSUE TITLE
Hanging at Installing OSInstall.mpkg

### ISSUE THREAD

**Issue by peteostro** [MagerValp/AutoDMG#159]
On a system with a fresh Install of OS 10.12 Final from external HD. Using autoDMG with the same installer (and iTunes 12.5.1 update in apply updates)  AutoDMG just hangs at the installing OSinstall.mpkg step. Activity monitor shows no CPU activity for AutoDMG.

**Comment by peteostro** [comment]
Looks like a reboot and uncheck of itunes 12.5.1 update cleared this up for me

**Comment by MagerValp** [comment]
Glad you got it sorted out. The iTunes installer is particular about certain things running and will hang if for example iTunes or Xcode is running. As you discovered, when building images with updates it's best to run it on a quiet system with few other things running.
