### ISSUE TITLE
AutoDMG set language setting to English

### ISSUE THREAD

**Issue by loutig** [MagerValp/AutoDMG#161]
Hello and thank you for your job!

I'm trying to use AutoDMG to deploy my Mac.
The problem is, the language settings automatically set to English at the installation (I want french).
The installation is manual with the recovery.

I use AutoDMG 1.6 through a French system 10.11.6.

**Comment by cgerke** [comment]
This isn't really a problem. AutoDMG isn't designed to localise, you'd need a postflight package for that.

**Comment by cgerke** [comment]
I can point you in the direction of some example scripts tomorrow. It depends on your use case.

**Comment by loutig** [comment]
Ok.
I thought he use the language of the system used to create the image ^^'.
Ma case is very simple. I just want to set French for all Mac.

**Comment by cgerke** [comment]
So there is a couple ways to do this depending on your setup. ie, do you have a configuration manager in your infrastructure etc etc.

Apple is heading and I can see in the not too distant future that this is the only viable way to manage configs for macs. But that is just my opinion.

Some people bake in tools like https://github.com/chilcote/outset to their autodmg and others bootstrap configuration managers such as chef, you can also import these settings via munki.

The simplest method would be to simple create a package that places a mobileconfig into your AutoDMG file at /private/var/db/ConfigurationProfiles/Setup

I was also going to suggest you just add a line to installesdtodmg.sh and had a quick look at it...and you know what...it is actually trying to set language after all :) so this may actually be an issue.

https://github.com/MagerValp/AutoDMG/blob/master/AutoDMG/installesdtodmg.sh#L161

On you build machine, what does this command output?

``` /usr/libexec/PlistBuddy -c "print :AppleLanguages:0" /Library/Preferences/.GlobalPreferences.plist ```

**Comment by MagerValp** [comment]
AutoDMG uses the system language to provide defaults for the Setup Assistant, but if you skip the assistant it will boot unlocalized (which effectively makes it en-US). If you create the dmg on a French system and then boot to the Setup Assistant, it should suggest France with a French keyboard in the dialog, just like a store bought machine.

**Comment by MagerValp** [comment]
Please try [AutoDMG 1.6.1b464](https://www.dropbox.com/s/3sk6tw4m23f4ql6/AutoDMG-1.6.1b464.dmg).

**Comment by MagerValp** [comment]
Fixed in 1.7.

**Comment by loutig** [comment]
Thanks very much!
I'm sorry, i'm so busy (think i'm going crazy) that i don't help you...

**Comment by MagerValp** [comment]
No worries, we found the bug in the end :)
