### ISSUE TITLE
AutoDMG only showing "United States" for Country

### ISSUE THREAD

**Issue by dianabirsan** [MagerValp/AutoDMG#163]
I used the 10.12.1 installer to create a dmg and it looks like I only have one country option when deploying through Casper Imaging.

**Comment by arubdesu** [comment]
Please see #161 for more discussion on this topic

**Comment by MagerValp** [comment]
Please try [AutoDMG 1.6.1b464](https://www.dropbox.com/s/3sk6tw4m23f4ql6/AutoDMG-1.6.1b464.dmg).

**Comment by MagerValp** [comment]
Fixed in 1.7.
