### ISSUE TITLE
_buildInstallPlanReturningError

### ISSUE THREAD

**Issue by ibrodowski** [MagerValp/AutoDMG#165]
To whom it may concern,

I was rebuilding a macOS Sierra 10.12.1 image and noticed the following debug messages:

- Info: installer.Debug:  Product archive /private/tmp/dmg.DSM2wY/Install iTunes.pkg trustLevel=501
- Info: installer.Debug:  -[IFDInstallController(Private) _buildInstallPlanReturningError:]: location = file://localhost
- Info: installer.Debug:  -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/private/tmp/dmg.DSM2wY/Install%20iTunes.pkg#iTunesX.pkg
- Info: installer.Debug:  -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/private/tmp/dmg.DSM2wY/Install%20iTunes.pkg#iTunesAccess.pkg
- Info: installer.Debug:  -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/private/tmp/dmg.DSM2wY/Install%20iTunes.pkg#CoreFP.pkg
- Info: installer.Debug:  -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/private/tmp/dmg.DSM2wY/Install%20iTunes.pkg#CoreADI.pkg
- Info: installer.Debug:  -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/private/tmp/dmg.DSM2wY/Install%20iTunes.pkg#MobileDevice.pkg
- Info: installer.Debug:  Set authorization level to root for session

These messages also appears for DMG and PKG files that are added for inclusion; like Google Chrome or Firefox.

Are these debug messages safe to ignore?

Thanks!

**Comment by MagerValp** [comment]
Yes, I think they are safe to ignore. They come from `/usr/sbin/installer`, and the method called is named `buildInstallPlanReturningError:`, which I take to mean that it builds an install plan and returns an error, or in this case `nil` indicating no error.
