### ISSUE TITLE
Autodmg won't open on Sierra 10.12.1

### ISSUE THREAD

**Issue by lowkeyshift** [MagerValp/AutoDMG#166]
Error message when trying to start autodmg. Looks like pyobjc isn't installed, but I installed it before I upgraded to Sierra.

> ImportError: No module named objc
> 2016-11-30 19:11:08.218 AutoDMG[8842:54248] UncaughtExceptionHandler:
> 2016-11-30 19:11:08.219 AutoDMG[8842:54248] Import of main.py failed
> 2016-11-30 19:11:08.219 AutoDMG[8842:54248] User info: (null)
> 2016-11-30 19:11:08.219 AutoDMG[8842:54248] Strack trace: (null)
> 2016-11-30 19:11:08.219 AutoDMG[8842:54248] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Import of main.py failed'
> *** First throw call stack:
> (
> 	0   CoreFoundation                      0x00007fff9958848b __exceptionPreprocess + 171
> 	1   libobjc.A.dylib                     0x00007fffade87cad objc_exception_throw + 48
> 	2   CoreFoundation                      0x00007fff9960696d +[NSException raise:format:] + 205
> 	3   AutoDMG                             0x000000010d4b41bc AutoDMG + 4540
> 	4   libdyld.dylib                       0x00007fffae766255 start + 1
> )
> libc++abi.dylib: terminating with uncaught exception of type NSException
>
>Abort trap: 6

**Comment by MagerValp** [comment]
Try uninstalling any 3rd party Python or PyObjC, AutoDMG relies on Apple's version that ships with macOS.
