### ISSUE TITLE
macO Sierra 10.12.2 (16C68) unknown build

### ISSUE THREAD

**Issue by donmontalvo** [MagerValp/AutoDMG#168]
So macO Sierra 10.12.2 (16C68) dropped on Tuesday. Isn't recognized by 1.7.1. I updated profiles, but no go.

**Comment by pudquick** [comment]
FYI, this is documented in the wiki

https://github.com/MagerValp/AutoDMG/wiki/Maintaining-Update-Profiles

https://github.com/MagerValp/AutoDMGUpdateProfiles#suggested-workflow

**Comment by MagerValp** [comment]
They dropped 16C67 Tuesday, but then sneakily dropped 16C68 last night without telling anyone. The profile was updated this morning though.

**Comment by donmontalvo** [comment]
#BeerForYouOneDay
