### ISSUE TITLE
AutoDMG 1.7.2 not launching successfully

### ISSUE THREAD

**Issue by rtrouton** [MagerValp/AutoDMG#170]
AutoDMG 1.7.2 is crashing on launch in the following situation:

Application version: AutoDMG v1.7.2 build 506
OS version: macOS Sierra 10.12.2 build 16C68

AutoDMG is being launched inside a VMware Fusion VM running macOS 10.12.2 build 16C68. Error message is shown below:

![screen shot 2016-12-19 at 1 33 05 pm](https://cloud.githubusercontent.com/assets/618055/21324675/c8901dea-c5f0-11e6-8345-f3e3cdb9442d.png)

Logfile:

[https://gist.github.com/rtrouton/89db8c3fc31bd9510b8ba90c1e93cda6](https://gist.github.com/rtrouton/89db8c3fc31bd9510b8ba90c1e93cda6)

AutoDMG 1.7.1 is launching successfully in the same VM.

**Comment by MagerValp** [comment]
1.7.2 crashes on startup if `~/Library/Application Support/AutoDMG/UpdateProfiles.plist` isn't already present. Fixed in 1.7.3.
