### ISSUE TITLE
Feature Request: Allow customized volume name

### ISSUE THREAD

**Issue by KRobinson-PHS** [MagerValp/AutoDMG#172]
We are using AutoDMG for our LANDesk deployments and we like to customize the volume name. It looks like it's fixed to "Macintosh HD" Would be nice to have an additional options button that would reveal a slide out tab with advanced options like, volume name. This would also lend it's self a place to put more features and advanced settings.

**Comment by KRobinson-PHS** [comment]
Also on a side note, I have forked this repo and will have a go at implementing this request for you if I can find the time. I like to hack around Xcode in my very little spare time.

**Comment by arubdesu** [comment]
You could save yourself the effort, if you want to use the CLI:
https://github.com/MagerValp/AutoDMG/wiki/Templates#volumename-string-defaultmacintosh-hd

**Comment by MagerValp** [comment]
As Allister writes it's available in templates, and you can find it in the GUI under Window -> Advanced Options ⇧⌘A.
