### ISSUE TITLE
Updating AutoDMG and profiles behind a proxy

### ISSUE THREAD

**Issue by grahampugh** [MagerValp/AutoDMG#173]
The built-in updaters do not seem to use system proxy settings, nor is there an option to set them manually. 

I have verified this by attempting to update using our corporate wired and wireless networks, which use automatic proxy settings using a PAC file, which fails, then tethering to my phone and trying again, which works.

**Comment by MagerValp** [comment]
@hunty1 reported the same thing, but unfortunately I'm not sure what the problem could be. I'm using Cocoa's standard NSURLConnection which automatically uses the system's proxy settings. It works fine here if I configure a standard SOCKS proxy. Is there anything particular in your PAC config that could cause an issue? What's the error in AutoDMG's log when it fails? And could you please run the following small python program and paste the output here:

    #!/usr/bin/python
    
    from Foundation import *
    
    url = NSURL.URLWithString_(u"https://automac.se/test.txt")
    request = NSURLRequest.requestWithURL_(url)
    data, response, error = NSURLConnection.sendSynchronousRequest_returningResponse_error_(request, None, None)
    if data:
        print "Data:"
        print NSString.alloc().initWithData_encoding_(data, NSUTF8StringEncoding).encode(u"utf-8")
    if response:
        print "Response:"
        print response
    if error:
        print "Error:"
        print error

**Comment by hunty1** [comment]
Running 10.12.2,

Using PAC - We get our PAC URL from DHCP option 252

![screen shot 2017-01-30 at 2 14 21 pm](https://cloud.githubusercontent.com/assets/7887711/22411379/54c793de-e6f7-11e6-9ccd-fb210c7f98ae.png)

Running the script produces this:

```
./test.py 
2017-01-16 15:20:48.523 Python[34048:402079] App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.
Error:
Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x7fce8b8dc3a0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://automac.se/test.txt, NSErrorFailingURLKey=https://automac.se/test.txt, _kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4, NSLocalizedDescription=The request timed out.}}, NSErrorFailingURLStringKey=https://automac.se/test.txt, NSErrorFailingURLKey=https://automac.se/test.txt, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.}
```

Using manual system proxy settings:

![screen shot 2017-01-30 at 2 13 35 pm](https://cloud.githubusercontent.com/assets/7887711/22411389/775e5090-e6f7-11e6-8dd1-b6ad39bc57aa.png)

The script produces this:

```
./test.py 
Data:
Don't dream it, be it.

Response:
<NSHTTPURLResponse: 0x7fe9d80897d0> { URL: https://automac.se/test.txt } { status code: 200, headers {
    "Accept-Ranges" = bytes;
    Age = 595;
    Connection = "keep-alive";
    "Content-Encoding" = gzip;
    "Content-Length" = 41;
    "Content-Type" = "text/plain";
    Date = "Mon, 30 Jan 2017 03:11:51 GMT";
    Etag = "\"a503d033-17-54712f6cc1e00\"";
    "Last-Modified" = "Fri, 27 Jan 2017 12:54:19 GMT";
    Server = Apache;
    Vary = "Accept-Encoding";
    Via = "1.1 varnish (Varnish/5.0)";
    "X-Varnish" = "453478678 445942475";
} }
```

Maybe its a bug?

**Comment by hunty1** [comment]
FWIW,

I tested the same process on 10.11.6 and did not get the ATS issue

**Comment by MagerValp** [comment]
Well that's weird, I'm requesting an https URL, yet with your PAC config you get the ATS warning about cleartext. Is the PAC URL itself http rather than https? I wonder if ATS is blocking access to the PAC config itself. Please try this one with PAC:

    #!/usr/bin/python
    
    from Foundation import *
    
    bundle = NSBundle.mainBundle()
    info = bundle.localizedInfoDictionary() or bundle.infoDictionary()
    info[u"NSAppTransportSecurity"] = {u"NSAllowsArbitraryLoads": True}
    
    url = NSURL.URLWithString_(u"http://automac.se/test.txt")
    request = NSURLRequest.requestWithURL_(url)
    data, response, error = NSURLConnection.sendSynchronousRequest_returningResponse_error_(request, None, None)
    if data:
        print "Data:"
        print NSString.alloc().initWithData_encoding_(data, NSUTF8StringEncoding).encode(u"utf-8")
    if response:
        print "Response:"
        print response
    if error:
        print "Error:"
        print error

**Comment by hunty1** [comment]
Hi Per,

Yep the PAC file is http. I thought that it might be the cause later but forgot to test and post back.

I'll give that new script a go when I get to work tomorrow

I remember other projects having to the the AllowArbitraryLoads thing. I think Munki might even do it to get around it.

And yep here it is:
https://github.com/munki/munki/blob/master/code/client/munkilib/gurl.py#L96-L100

**Comment by MagerValp** [comment]
Munki has AllowArbitraryLoads set because admins can serve their repos over http, but AutoDMG only fetches resources over https.

**Comment by hunty1** [comment]
Then this must be a bug in NSURLConnection on 10.12 that is causing the request for the PAC file over http to trip the ATS

As i mentioned, I tested the script on 10.11 and it worked correct for a PAC file. Only on 10.12 did it fail.

Also tested AutoDMG on 10.11 and 10.12, it only fails to receive the profile on 10.12 with a PAC file.
10.11 with pac file is fine.

**Comment by MagerValp** [comment]
Interesting, thank you! Would you mind filing a radar with Apple about it? I could file it but since I don't have a proxy with PAC I couldn't answer any follow-up questions.

I'd prepare for the answer being that it's by design though. Having an unsecured proxy configuration control https traffic sounds like an easy way to MITM.

**Comment by erikng** [comment]
10000000% agreed.

On Jan 30, 2017, at 6:09 AM, Per Olofsson <notifications@github.com<mailto:notifications@github.com>> wrote:


Interesting, thank you! Would you mind filing a radar with Apple about it? I could file it but since I don't have a proxy with PAC I couldn't answer any follow-up questions.

I'd prepare for the answer being that it's by design though. Having an unsecured proxy configuration control https traffic sounds like an easy way to MITM.

-

**Comment by grahampugh** [comment]
I haven't yet had a chance to run your tests, but just to note that our
proxy PAC is also http. I will attempt the tests tomorrow, but note with
interest your comment about security.

Cheers
Graham

**Comment by hunty1** [comment]
Tested the updated script with the AllowArbitraryLoads. It works as expected.

I will log a bug report with Apple. Tested on 10.12.2 and 10.12.3 FWIW

Interesting that this is a change in behaviour from 10.11.6 though. ¯\_(ツ)_/¯

**Comment by erikng** [comment]
Not really. Apple is rewriting everything in Swift and trying to secure the platform as much as possible. I would start discussing with your security team to move to https. I doubt Apple will fix this.

On Jan 30, 2017, at 10:46 PM, Calum <notifications@github.com<mailto:notifications@github.com>> wrote:


Tested the updated script with the AllowArbitraryLoads. It works as expected.

I will log a bug report with Apple. Tested on 10.12.2 and 10.12.3 FWIW

Interesting that this is a change in behaviour from 10.11.6 though. ?_(?)_/?

-

**Comment by MagerValp** [comment]
@grahampugh @hunty1 Have you received any feedback from Apple about this?

**Comment by hunty1** [comment]
Sorry completely forgot about this.

https://openradar.appspot.com/radar?id=5013622782689280

**Comment by MagerValp** [comment]
Thanks, that more or less confirms the problem is what we suspected. For reference, do you have the id of the radar it was closed as a duplicate of?

**Comment by hunty1** [comment]
29752997 was the original and has since been marked as closed
30299463 was mine and was marked as dupe and closed

**Comment by MagerValp** [comment]
Thanks!
