### ISSUE TITLE
Pre-compile .pyc files for code signing benefits

### ISSUE THREAD

**Issue by arubdesu** [MagerValp/AutoDMG#174]
As suggested by @ccaviness, please consider pre-compiling the associated .pyc files when building/signing a new release. Not sure how you target the artifacts in the build folder, definitely a lower priority if it doesn't also help performance or other things you were interested in. 
```py
python -m compileall <path to AutoDMG>
```

**Comment by MagerValp** [comment]
Instead of precompiling the pycs I disabled generation of them. Please try [AutoDMG 1.7.4b521](https://www.dropbox.com/s/lmzq2ijw1yafk4z/AutoDMG-1.7.4b521.dmg).
