### ISSUE TITLE
AutoDMG fails when creating disk image MacOS10.12.3

### ISSUE THREAD

**Issue by erchyo** [MagerValp/AutoDMG#175]
running latest AutoDMG.
freshly built system.
fresh download of the installer

fails at the same point each time,  log attached.

any  help would be greatly appreciated.

[AutoDMG log 32017.txt](https://github.com/MagerValp/AutoDMG/files/855638/AutoDMG.log.32017.txt)

**Comment by MagerValp** [comment]
The OS installer stops right after it starts with: "An error occurred installing macOS. To use Apple Diagnostics to check your Mac hardware, shut down, press the power button, and immediately hold the ‘D’ key until diagnostics begins."

I'm afraid it's hard to provide any useful analysis of why Apple's installer fails. Does it persist after a reboot? Have you tried on another computer?

**Comment by erchyo** [comment]
it persist after a reboot. Ill try it on different hardware now.

**Comment by erchyo** [comment]
just tried it on different hardware (also running 10.12.3)  looks like the same error
[AutoDMG 2017-03-20 13.52.txt](https://github.com/MagerValp/AutoDMG/files/855884/AutoDMG.2017-03-20.13.52.txt)

**Comment by erchyo** [comment]
It dawned on me I was using the same copy of the installer on both machines.  I got a fresh copy and it did not error out.

thank you for you time :-)

**Comment by MagerValp** [comment]
Interesting, glad you figured it out.
