### ISSUE TITLE
App Transport Security Policy failure

### ISSUE THREAD

**Issue by scifiman** [MagerValp/AutoDMG#177]
I saw the other bug with the Proxy causing a similar effect but I don't think this is related.
On 10.11.6, using AutoDMG 1.7.3, I am getting a "Download Failed" message.  This occurs when I go to download updates to the OS X Installer. (Remote Desktop, iTunes, etc.)
The error is
> The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.

There is no proxy in the way and this is a fresh VM.  The network is assigned to its own port, not shared with the host.

I just went through this process on a fresh 10.12.3 Sierra VM last week with no issues so it much be something specific to El Capitan.

**Comment by MagerValp** [comment]
I built a fully patched 10.11.6 image yesterday in VMware, so I'm afraid I can't seem to reproduce this. Can you try again and attach the log?

**Comment by scifiman** [comment]
Finally got back to this.  Log attached.
Seems to be a problem with the Remote Desktop update?
I am on a university campus currently so about to try from a VZW hotspot.
[AutoDMG 2017-04-17 10.40.log.txt](https://github.com/MagerValp/AutoDMG/files/925963/AutoDMG.2017-04-17.10.40.log.txt)

**Comment by scifiman** [comment]
On the hotspot, the download completed successfully.  Weird that my 10.12 image didn't have an issue but it also didn't have this update (Remote Desktop) when I built it.
Looks like it may be a corrupt update somewhere in the chain.
I believe we do have a Qwilt caching server on campus.  Looks like I have to talk to networking and see if we can dump this cached file.

So, no issue with AutoDMG.  Issue can be closed.
Thanks for continuing to work on this great piece of software!

**Comment by MagerValp** [comment]
Glad you figured it out, thanks!
