### ISSUE TITLE
AutoDMG Fails to accept 10.13 Beta Installer

### ISSUE THREAD

**Issue by TinyAtJamf** [MagerValp/AutoDMG#180]
The error was "Error finding version" upon dragging and dropping the Installer.

Opening AutoDMG on a 10.13 Mac to make a 10.13 Base OS.

After doing the workflow, the items in the installer are hidden. They don't show up in the finder, but are there with an 'ls' in terminal.

**Comment by MagerValp** [comment]
Thanks, already on it, Apple changed the installer in 10.13 and support is being developed in the [highsierra](https://github.com/MagerValp/AutoDMG/commits/highsierra) branch.
