### ISSUE TITLE
Image Build Failing - Both GUI and CLI

### ISSUE THREAD

**Issue by RMurphy120** [MagerValp/AutoDMG#182]
I've been having an issue where at the very end of the process, the build fails. While using the GUI, it comes back with a failure code of "2" with no other explanation.

I tried running it through CLI with logging, and got this:

```
July 17, 2017 at 12:31:24 PM PDT  Starting phase: Scanning disk image
July 17, 2017 at 12:31:24 PM PDT  phase: Scanning disk image
July 17, 2017 at 12:31:25 PM PDT  progress: 99.6%
July 17, 2017 at 12:31:26 PM PDT  progress: 99.8%
July 17, 2017 at 12:31:27 PM PDT  progress: 99.9%
July 17, 2017 at 12:31:28 PM PDT  progress: 100.0%
July 17, 2017 at 12:31:30 PM PDT  asr output: Couldn't unmount device /dev/disk6s2
July 17, 2017 at 12:31:36 PM PDT  asr output: unable to write UDIF info into "/Users/rmurphy/Desktop/Sierra-Build.dmg" - Resource temporarily unavailable.
July 17, 2017 at 12:31:36 PM PDT  asr output: asr: image scan failed - Resource temporarily unavailable.
July 17, 2017 at 12:31:36 PM PDT  Task exited with status 1
July 17, 2017 at 12:31:36 PM PDT  Workflow failed: Build failed (Task exited with status 1)
July 17, 2017 at 12:31:36 PM PDT  Build failed: Build failed
July 17, 2017 at 12:31:36 PM PDT      Task exited with status 1
```

Clearly, there is an issue unmounting the disk and writing info into the .dmg file. Any ideas?

**Comment by RMurphy120** [comment]
Restarting the machine fixed the issue. Is there a way to fix this without restarting, or can you please explain to me what exactly is happening? Pretty new to this. Thanks!

**Comment by TinyAtJamf** [comment]
Been seeing this on 10.12.6 pretty frequently during testing. Restarting the machine helps sometimes, otherwise I watch for when it fail the unmount and manually unmount the drive through Terminal. Maybe it just needs an extra time to become "not busy".

**Comment by MagerValp** [comment]
It's hard to say why exactly the dmg mount is being "clingy" — it could be an OS bug, it could be third party software running (e.g. antivirus), it could be something you installed in the image. Since it causes `asr` to fail, there's precious little that AutoDMG can do except abort. The error message could be more descriptive though, I'll see if I can make it a little clearer.
