### ISSUE TITLE
Build failed (Task exited with status 13)

### ISSUE THREAD

**Issue by ftiff** [MagerValp/AutoDMG#186]
Using Version 1.8b (537) on 10.13 Beta (17A358a) on APFS disk.

Sorry I cannot be of better help… just this report

> 29 August 2017 at 21:48:21 CEST  installer.Info:  AutoPkgr is a valid target.
> 29 August 2017 at 21:55:45 CEST  Task exited with status 13
> 29 August 2017 at 21:55:45 CEST  Workflow failed: Build failed (Task exited with status 13)
> 29 August 2017 at 21:55:52 CEST  (IEDWorkflow:514) Workflow stopping
> 29 August 2017 at 21:55:52 CEST  (IEDWorkflow:97) Detaching installer DMGs
> 29 August 2017 at 21:55:52 CEST  (IEDDMGHelper:187) Detaching /Users/fti/Library/Application Support/AutoDMG/Updates/iTunes12.6.2(fe2e229).dmg
> 29 August 2017 at 21:55:52 CEST  (IEDDMGHelper:202) Detaching /Users/fti/Library/Application Support/AutoDMG/Updates/iTunes12.6.2(fe2e229).dmg, attempt 1/5
> 29 August 2017 at 21:55:52 CEST  (IEDUpdateController:102) enableControls

[AutoDMG-2017-08-29.txt](https://github.com/MagerValp/AutoDMG/files/1261564/AutoDMG-2017-08-29.txt)

**Comment by ftiff** [comment]
subsequent run went fine 🤔

**Comment by ftiff** [comment]
Now that I'm less stressed: THANK YOU! 👍 🥇 💯

**Comment by MagerValp** [comment]
Not a lot to go on I'm afraid, the OS installer failed with error 13 somewhere between 21:48:21 and 21:55:45:

    29 August 2017 at 21:48:21 CEST  installer.Info:  AutoPkgr is a valid target.
    29 August 2017 at 21:55:45 CEST  Task exited with status 13

You might find something in the system log between those timestamps, but I wouldn't hold my breath...
