### ISSUE TITLE
10.13 Force HFS+?

### ISSUE THREAD

**Issue by peteostro** [MagerValp/AutoDMG#187]
Notice using AutoDMG on a 10.13 spinning disk based mac (HFS+) it still created the OS Image as APFS.
When deploying an APFS image with DeployStudio to a spinning disk based mac (with 10.3 firmware update) the deploy will fail (on purpose, DS currently checks to make sure you deploy APFS image on to a SSD)
Need a way to force HFS+ image creation with 10.13

**Comment by MagerValp** [comment]
The GM dropped and the release notes confirm that APFS will be unsupported on some 3 TB Fusion Drive setups, so I'm adding an HFS option. Note that APFS is supported on spinning disks, it's only automatic conversion during install that isn't, so I think it's unwise for DeployStudio to block that.

**Comment by peteostro** [comment]
Thanks! Any way to donate $ to this project?

**Comment by MagerValp** [comment]
[1.8b541](https://github.com/MagerValp/AutoDMG/releases/tag/v1.8b541) posted with HFS support, please give it a spin.

No way to donate, but testing is always appreciated :)

**Comment by peteostro** [comment]
tested out 1.8.B41 and working good for both apfs and hfs+ on 10.13 GM

**Comment by MagerValp** [comment]
👍🏼
