### ISSUE TITLE
Drag And Drop not working

### ISSUE THREAD

**Issue by dorminyk** [MagerValp/AutoDMG#192]
I recently upgraded my os to 10.13.0 and have the newer version of AutoDMG. When I try and grab the "Install macOS High Sierra.app" from my applications folder and try and drop it in the GUI, it will not accept the function.

To get around this, I had went to File > Select Installer and was able to select the file to use.

**Comment by MagerValp** [comment]
Closing as I'm afraid I can't reproduce the problem.
