### ISSUE TITLE
Restore image

### ISSUE THREAD

**Issue by chris1111** [MagerValp/AutoDMG#194]
command line **asr** unable to restore APFS image on HFS + J or APFS volumes
always the same error ( **HFS+ Output error** Could not change the partition type for /dev/disk5s2
**APFS output error** 
mount_apfs: mount: Operation not permitted
 /sbin/mount failed with error 18688)

**this is the output of HFS+J Volumes** 
Last login: Sun Oct 15 13:05:11 on ttys000
iMac-de-chris:~ chris$ asr restore --source /$HOME/MacDeployment.dmg --target /Volumes/USB --erase --noverify
	Validating target...done
	Validating source...done
	Erase contents of /dev/disk5s2 (/Volumes/USB)? [ny]: y
	Repartitioning target device...
Could not change the partition type for /dev/disk5s2 - Autorisation refusée
iMac-de-chris:~ chris$ 

![capture](https://user-images.githubusercontent.com/6248794/31587142-2a0bce02-b1aa-11e7-9b54-387ac64a90f0.png)

**this is the output of APFS Volumes** 
Last login: Sun Oct 15 13:38:26 on ttys000
iMac-de-chris:~ chris$ asr restore --source /$HOME/MacDeployment.dmg --target /Volumes/USB --erase --noverify
	Validating target...done
	Validating source...done
mount_apfs: mount: Operation not permitted
/sbin/mount failed with error 18688

Couldn't copy preboot volume contents from image - Version RPC incorrecte
iMac-de-chris:~ chris$ 

![capture](https://user-images.githubusercontent.com/6248794/31587353-6cedb178-b1ae-11e7-88cf-b432e1dae073.png)

but in Disk Utility thats work, strange ?
Thanks

**Comment by chris1111** [comment]
![capture](https://user-images.githubusercontent.com/6248794/31587345-49c990e0-b1ae-11e7-9438-496e003a7138.png)

**Comment by arubdesu** [comment]
Hey Chris, this isn't really an issue with the AutoDMG code, is it? I would think you'd need `sudo` at the beginning of the command.

**Comment by chris1111** [comment]
Exact you are right this is not a problem with the code AutoDMG and sudo its works thank you very much
