### ISSUE TITLE
AutoDMG 1.8 with HighSierra couldn't find system version

### ISSUE THREAD

**Issue by zrebie** [MagerValp/AutoDMG#197]
## Description of issue

We are trying to build an image using AutoDMG 1.8 with 10.13.1 InstallESD.dmg. Off course we are doing it on a mac mini with HighSierra 10.13.1 installed on it. 
(Tried both GUI and command line)

## Expected behavior

Image is created

## Actual behavior

Error: "Couldn't find system version"

## Steps to reproduce

1. Download 10.13.1
2. Run command:
sudo /Applications/AutoDMG.app/Contents/MacOS/AutoDMG -r -v build -o ~/provisioning/output/macOS_custom_output.dmg -f ~/provisioning/input/10.13.1/InstallESD.dmg 

## Log file

Running as root, using /var/root/Library/Application Support/AutoDMG
AutoDMG v1.8 build 548
Mac OS X 10.13.1 17B48
CPython 2.7.10 (GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31))
PyObjC 2.5.1
Setting source path to '/Users/svc_quickbuild/provisioning/input/10.13.1/InstallESD.dmg'
Setting output path to '/Users/svc_quickbuild/provisioning/output/macOS_custom_output.dmg'
Installer: /Users/svc_quickbuild/provisioning/input/10.13.1/InstallESD.dmg
Examining source…
Source failed: Invalid source
    Couldn't find system version.

**Comment by erikng** [comment]
Why aren't you using the .app!

Thanks,
Erik Gomez
________________________________

**Comment by gang65** [comment]
I have the same issue.
If I use app GUI instead od CLI, the result are the same. In error window there is message:

Couldn't find system version.

**Comment by MagerValp** [comment]
You have to use the installer app as the source for 10.13, InstallESD.dmg doesn’t contain everything needed to install the OS anymore.

**Comment by gang65** [comment]
Thank you. It is working perfectly after selecting installer app, instead of InstallESD.dmg.
