### ISSUE TITLE
There is no possibility to set case sensitive File System

### ISSUE THREAD

**Issue by gang65** [MagerValp/AutoDMG#198]
## Description of issue
With AutoDMG 1.8 the new option was added to select file system (APFS or HFS+):
Added APFS/HFS+ selection to the Advanced Options window.
Added -F/--filesystem option to CLI.

Unfortunately there is missing option to setup Case Sensitive File system.

For AutoDMG in version 1.7.3 case sensitive could be enabled for HFS+ file system, by changing from:

> if ! hdiutil create -size "${size}g" -type SPARSE -fs HFS+J -volname "$volname" -uid 0 -gid 80 -mode 1775 "$sparsedmg"; then 

to

> if ! hdiutil create -size "${size}g" -type SPARSE -fs "Case-sensitive Journaled HFS+" -volname "$volname" -uid 0 -gid 80 -mode 1775 "$sparsedmg"; then

It will be great to add option to select Case Sensitive File System by CLI or Advanced Options window.

**Comment by MagerValp** [comment]
I struggle to see a reason to enable it as It causes compatibility issues with major software packages. You’re free to keep editing the bash script if you absolutely need it.
