### ISSUE TITLE
10.13.1 (17B1002) created on MacBook Air vs 10.13.1 (17B1003) created on MacBook Touch ID

### ISSUE THREAD

**Issue by donmontalvo** [MagerValp/AutoDMG#200]
## Description of issue

Unless things changed, build numbers that include four numbers are model specific.

Iff MacBook Air and MacBook Touch ID give different builds, what's the verdict?

Both seem to work with both models...need a sanity check. :)

Both are 10.13.1 with all available updates (iTunes and Security Update [for root fiasco]).

https://www.jamf.com/jamf-nation/discussions/26326/10-13-1-17b1002-created-on-macbook-air-vs-10-13-1-17b1003-created-on-macbook-touch-id

## Expected behavior

One build number?

## Actual behavior

Two (at least) build numbers?

## Steps to reproduce

Press the button on different models to create OOB DMG.

**Comment by MagerValp** [comment]
https://github.com/MagerValp/AutoDMGUpdateProfiles/commit/55a4b2a628f925e667d598091c1c5f0fc30623c7
