### ISSUE TITLE
Weird python error when launching AutoDMG on High Sierra 10.13.2

### ISSUE THREAD

**Issue by kbotnen** [MagerValp/AutoDMG#203]
## Description of issue

When starting AutoDMG it dies with uncaught exception. There is no way to "Save Log..." or "Quit" after the error. Only a forced kill will remove the window.

If I "reinstall" by copying the AutoDMG.app file from the DMG file it starts working again. I suspect that it might some issue with my disc.

A reboot of the machine also "fix" the "problem".

## Expected behavior

AutoDMG start its nice, clean UI where I can do magic stuff with .app files.

## Actual behavior

A window with the traceback og the exceptions is shown, and the buttons "Save Log..." and "Quit" are not respondong.

## Steps to reproduce

Start AutoDMG from the /Application folder. It does not fails on first start, but if I open it, use it and then close it. Then it might error on me when opening it later.

## Log file

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/PyObjCTools/AppHelper.py", line 239, in runEventLoop
    main(argv)
  File "/Applications/AutoDMG.app/Contents/Resources/IEDUpdateController.py", line 47, in init
    self.cache = IEDUpdateCache.alloc().initWithDelegate_(self)
  File "/Applications/AutoDMG.app/Contents/Resources/IEDUpdateCache.py", line 43, in initWithDelegate_
    self = self.init()
  File "/Applications/AutoDMG.app/Contents/Resources/IEDUpdateCache.py", line 33, in init
    self.updateDir = os.path.join(url.path(), "AutoDMG", "Updates")
AttributeError: 'NoneType' object has no attribute 'path'

**Comment by MagerValp** [comment]
My best guess is that the account you ran AutoDMG from was lacking a `~/Library/Application Support` directory. AutoDMG 1.8.1 should log a nicer error message.
