### ISSUE TITLE
AutoDMG does not show apples macOS High Sierra 10.13.2 Supplemental Update

### ISSUE THREAD

**Issue by peteostro** [MagerValp/AutoDMG#204]
## Description of issue

foo

## Expected behavior

bar

## Actual behavior

baz

## Steps to reproduce

1. xxx
2. yyy
3. zzz

## Log file

_(Save the debug log and attach it by dragging it here)_

**Comment by peteostro** [comment]
When creating a new image with AutoDMG the macOS High Sierra 10.13.2 Supplemental Update is not shown in list of updates available. (this is the spectre cpu bug update)

**Comment by MagerValp** [comment]
The supplemental update isn't compatible with AutoDMG and has to be applied to a live system.

**Comment by peteostro** [comment]
thanks
