### ISSUE TITLE
Security Update 2018-001 not showing up (El Capitan)

### ISSUE THREAD

**Issue by Jinnzz** [MagerValp/AutoDMG#205]
## Description of issue

The latest Security Update 2018-001 (El Capitan) does not show up when the Profiles are updated.It shows the Security Update 2017-005 (El Capitan).Manually editing the UpdateProfiles.plist fixes the issue though.

**Comment by arubdesu** [comment]
Hey @Jinnzz welcome to github!
You mean the _label_ or name of the update, not the update itself, correct? The download location and hash of it was bumped, so you’re just having a cosmetic issue, right?
https://github.com/MagerValp/AutoDMGUpdateProfiles/commit/f3b96043e8415ec7d21259e66962fbdd7eeb7bc6#diff-0cf12fa731f5992520167bee9eaf57ba

**Comment by Jinnzz** [comment]
Thanks!Yep i believe you are correct my bad.Could have sworn it was more because the Update folder was showing the 2017 update shortcut as well.

**Comment by MagerValp** [comment]
Typo fixed, thanks!
