### ISSUE TITLE
Unknown build for Mac OS X 10.11.6 15G1011

### ISSUE THREAD

**Issue by LordGreystoke007** [MagerValp/AutoDMG#207]
## Description of issue

Unknown build for Mac OS X 10.11.6 15G1011

## Expected behavior

That AutoDMG recognize 15G1011

## Actual behavior

AutoDMG fails to recognize 10.11.6 (15G011) and fails when you try to build

## Steps to reproduce

1. Start AutoDMG
2. Drag El Capitan Installer on to AutoDMG

## Log file

_(Save the debug log and attach it by dragging it here)_

**Comment by MagerValp** [comment]
Closing, as 10.11 support is removed with AutoDMG 1.9.
