### ISSUE TITLE
Supplemental Updates

### ISSUE THREAD

**Issue by daroloson** [MagerValp/AutoDMG#208]
![autodmg10 13 3](https://user-images.githubusercontent.com/13855059/36798725-5e594678-1c79-11e8-8270-c0a6562bff13.png)

Shouldn't Supplemental Updates be detected and show up in the updates section?

If not, are there reasons to avoid adding them to the Additional software section?

**Comment by MagerValp** [comment]
The supplemental updates didn't work when installed in an image.
