### ISSUE TITLE
AutoDMG App Transport Security policy requires the use of a secure connection

### ISSUE THREAD

**Issue by MACauffman** [MagerValp/AutoDMG#212]
## Description of issue

Download of Updates for MacOSX 10.11.6 fails to download Security Update 2018-002 (El Capitan)

## Expected behavior

All updates download when clicking "Download" button

## Actual behavior

First two updates download with error dialog on the third with says:
"The resource could not be loaded because the App Transport Security policy requires the use of a secure connection."

## Steps to reproduce

1. Drag OSX 10.11.6 installer to AutoDMG
2. Checked Apply Updates
3. Clicked "Download" button to download update pkgs

## Log file

_(Save the debug log and attach it by dragging it here)_
[AutoDMG 2018-04-23 17.41.log](https://github.com/MagerValp/AutoDMG/files/1940139/AutoDMG.2018-04-23.17.41.log)

**Comment by MagerValp** [comment]
This is fixed in 1.8.1.
