### ISSUE TITLE
Download failed: Security Update 2018-003 (El Capitan) failed with HTTP 403

### ISSUE THREAD

**Issue by ebonfyre** [MagerValp/AutoDMG#216]
## Description of issue

Attempting to "Apply Updates" to Mac OS X 10.11.6 image using AutoDMG 1.8.1 fails with error message "Download failed: Security Update 2018-003 (El Capitan) failed with HTTP 403".  Downgrading to AutoDMG 1.7.3 also fails with error message "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection".

Manually downloading the update from Apple fails using the link in the AutoDMG UpdateProfiles.plist but succeeds when searching for the update on support.apple.com... but I have no way of manually adding this to your handy "Apply Updates" cache folder in Application Support because it disappears when I do and launch AutoDMG.

## Expected behavior

Apply Updates checkbox should download and apply updates.

## Actual behavior

Error messages on Security Update 2018-003

## Steps to reproduce

1. Drag "Install OS X El Capitan" onto AutoDMG window
2. Check "Apply updates" box
3. Click "Download" button

## Log file

Not applicable

**Comment by MagerValp** [comment]
Looks like Apple changed the download URL, fixed now.
