### ISSUE TITLE
Unable to build 10.13.6 - "Low battery status changed: 0" loop

### ISSUE THREAD

**Issue by bvp663** [MagerValp/AutoDMG#219]
## Description of issue

Running MaxOS 10.13.6 (17G65) downloaded from the App Store and applying iTunes 12.8 update. The logs get stuck running `Low battery status changed: 0`

## Expected behavior

Build should complete in ~ hour

## Actual behavior

Left running for over 2 hours without a build ever completing. Logs seems to show it stuck on a command. The GUI shows it working on the `Installing Installinfo.plist` 

## Steps to reproduce

1. Drag `Install MacOS High Sierra` installer onto AutoDMG, select Apply Updates for iTunes 12.8
2. Build

## Log file

[AutoDMG 2018-07-13 13.42.log](https://github.com/MagerValp/AutoDMG/files/2194133/AutoDMG.2018-07-13.13.42.log)

**Comment by MagerValp** [comment]
This is likely an issue with Apple's installer, rather than something AutoDMG does. FWIW I can't reproduce it and 10.13.6 builds just fine here. Have you tried rebooting, or running on a different machine?
