### ISSUE TITLE
10.14b4+ fails to build

### ISSUE THREAD

**Issue by MagerValp** [MagerValp/AutoDMG#223]
## Description of issue

Trying to build an image with Mojave b4+ fails.

## Expected behavior

A successfull built system image.

## Actual behavior

AutoDMG fails with "Installation of 'InstallInfo.plist' failed with return code 1. See the log for details."

## Steps to reproduce

1. Download `Install macOS Mojave Beta.app` b4 or newer, and store it on a secondary volume (see issue #222)
2. Select the installer as the source in AutoDMG and click Build.

## Log file

[AutoDMG-2018-08-14.log](https://github.com/MagerValp/AutoDMG/files/2287361/AutoDMG-2018-08-14.log)

**Comment by osXCanada** [comment]
version 1.9!! I checked updates on the app, it said I was...but one actually has to check the website. Sorry for my misinformed post!
