### ISSUE TITLE
apfs inverter failed to invert the volume

### ISSUE THREAD

**Issue by scheblein** [MagerValp/AutoDMG#224]
## Description of issue

Using asr in recovery to restore the AutoDMG created image results in an error message "apfs inverter failed to invert the volume".

## Expected behavior

restore completes successfully

## Actual behavior

restore failed with error "apfs inverter failed to invert the volume"

## Steps to reproduce

1. create dmg from install app using autodmg
2. boot 10.13.x mac (to restore) into recovery
3. open terminal and run command "asr restore -source /Volumes/Image\ Volume/osx-Xapfs.dmg -target /dev/diskXsX -erase"

## Question
What is the correct way to restore an autodmg file to a Mac running 10.13.x?

**Comment by MagerValp** [comment]
I'm sorry, but this is not an AutoDMG issue. As for restoring images, I'd recommend Imagr or Restor.
