### ISSUE TITLE
Unknown build 17G2208

### ISSUE THREAD

**Issue by daroloson** [MagerValp/AutoDMG#225]
Special build of 10.13.6 for MacBook Pro.

Tried both 1.8.1 and 1.9b572.

**Comment by erikng** [comment]
You have to build this on a T2 mac.

**Comment by daroloson** [comment]
<img width="1046" alt="screen shot 2018-09-10 at 12 51 52 pm" src="https://user-images.githubusercontent.com/13855059/45311834-64278200-b4f8-11e8-9699-4a2d8c4ffad2.png">

I am.

**Comment by daroloson** [comment]
<img width="861" alt="screen shot 2018-09-10 at 11 22 22 am" src="https://user-images.githubusercontent.com/13855059/45316581-510eb500-b4ec-11e8-886b-5bd246a52a62.png">

I am.

**Comment by erikng** [comment]
You can still build it. I think the build should stay unknown as we don't have any way to warn people that it won't work on non-t2 machines.

But there is nothing preventing you from building an image.

Thanks,
Erik Gomez
________________________________

**Comment by slappywhiteknows** [comment]
Same issue here, also on a T2 2018 MBP. Likely needs to have build 17G2208 referenced in the AutoDMG code as it errors out when it doesn't know about the build.

**Comment by daroloson** [comment]
I was able to build i.e. just ignore the warning.
Note: anything with a T2 won't NetBoot so I'm using Target Mode Imaging.
Also don't include the "macOS High Sierra 10.13.6 Supplemental Update 2 for MacBook Pro" in the build.

**Comment by slappywhiteknows** [comment]
Thanks, I am using a custom image script to create the image. The error is the same, but unfortunately can't be ignored.

**Comment by MagerValp** [comment]
Command line builds should work if you don't specify `--download-updates`, if it doesn't then that's a bug.

This should be moved to [AutoDMGUpdateProfiles](https://github.com/MagerValp/AutoDMGUpdateProfiles) though. PR's are welcome, I haven't had any time to build a profile for the split 10.13.6 builds.
