### ISSUE TITLE
Build failed InstallInfo.plist with return code 1

### ISSUE THREAD

**Issue by svh1985** [MagerValp/AutoDMG#227]
## Description of issue

Error when creating image. Tested images:

- 10.14 APFS and HFS on external disk
- 10.13 APFS and HFS on internal and external disk

## Actual behavior

Build failed InstallInfo.plist with return code 1

## Steps to reproduce

1. Download installer
2. Drag and drop
3. Click build

## Log file
[AutoDMG 2018-10-18 15.36.log](https://github.com/MagerValp/AutoDMG/files/2492114/AutoDMG.2018-10-18.15.36.log)

**Comment by junkman690** [comment]
Was it on a external USB or network drive. I experienced an issue building a 10.14.1 image from a network drive, but the same image built successfully once copied to a external USB.

**Comment by svh1985** [comment]
I had the installer on an External USB drive.

**Comment by MagerValp** [comment]
You're using 1.8, but 1.9 is needed for 10.14 support.
