### ISSUE TITLE
Unable to download Safari 12.1.1 for Serria 

### ISSUE THREAD

**Issue by Minspace32** [MagerValp/AutoDMG#236]
## Description of issue
While  trying to download Safari 12.1.1 for Serria. It fails to download with a 404 error. I have tried different machines and internet connections. 

## Expected behavior

Downloads update

## Actual behavior
Failed with HTTP 404 error 

## Steps to reproduce
1.Put latest Sarria  app into auto dmg
2.Click apply updates 
3. Click download
4.Download first 2 updates then fails on safari

## Log file

_(Save the debug log and attach it by dragging it here)_
[AutoDMG 2019-08-05 11.26.log](https://github.com/MagerValp/AutoDMG/files/3465591/AutoDMG.2019-08-05.11.26.log)

**Comment by arubdesu** [comment]
http://swcdn.apple.com/content/downloads/39/48/041-62930/6bwouqqzrf7uhexxs7z0k9ntun8ec0kmew/Safari12.1.2Sierra.pkg

**Comment by Jamyn** [comment]
https://github.com/MagerValp/AutoDMGUpdateProfiles/pull/80 should address your issue, if it is merged.
