### ISSUE TITLE
Feature Request: Option to Run Additional Software Pkgs. on First Boot

### ISSUE THREAD

**Issue by cv-rao** [MagerValp/AutoDMG#237]
## Description of issue

I am requesting a check box type feature that will allow when the install of Additional Software .pkg (s) takes place (during .dmg creation or post first boot)

additionally, the ability to set a default host name for the restored mac would be great!

## Expected behavior

i.e if a box is checked next to the .pkg (s) listed, that particular pkg will get installed on first boot of the restored .dmg on a target mac.

this behavior would be very similar to the "Postponed Installation (packages will be installed on first boot) option in DeployStudio.

additionally, the host name of the target mac can be custom set, similar to how the name of the boot hd can now be custom defined in Advanced Options.

## Actual behavior

Additional Software .pkgs are currently installed during the initial build of the os .dmg only.

additionally, the default host name of the restored mac is currently based on apple's user account name based host name.

## Steps to reproduce

such a feature would be very useful to install mdm agents from filewave, addigy and such, which require their installer packages to be run after the initial boot of the mac.

additionally, with the custom host name (perhaps even a choice to set
[DeployStudion First Boot Install.pdf](https://github.com/MagerValp/AutoDMG/files/3492326/DeployStudion.First.Boot.Install.pdf)
 the host name to the mac's serial number), would allow the newly restored mac to be identified in the mdm, where the host name can be changed to something else for further management.

## Log file

_(Save the debug log and attach it by dragging it here)_

**Comment by erikng** [comment]
Hey CV (been a very long time)! 

I feel like these features seem like feature creep. AutoDMG's purpose is to create an image, not be a provisioning process.

There's nothing stopping you from creating your own launch daemon/script (in a package installed by AutoDMG) that could be intelligent enough to not run until the machine was first booted. You could then even use a tool like LoginLog (also written by Per) to do this. 

That was actually the beginning stages of Imagr, which I hope you are familiar with.

If you really need something like this, you could even use a tool like InstallApplications, that you could preload into your image and it is intelligent enough to immediately start running upon first boot (though it does not come with a GUI - you must provide your own).

All of this to say, you have multiple options that you can already do, without requesting features that won't be utilized for very many people. The notion of imaging is dying and has been dying for years, so most people have moved to a different kind of provisioning process by now.

**Comment by MagerValp** [comment]
This is indeed out of scope for AutoDMG. Take a peek at [First_Boot_Package_Install_Generator](https://github.com/rtrouton/First_Boot_Package_Install_Generator), I think it accomplishes what you want.
