### ISSUE TITLE
AutoDMG v1.10b587 fails to create file macOS Catalina 10.15.4 Beta 19E224g

### ISSUE THREAD

**Issue by sebFischer** [MagerValp/AutoDMG#247]
## Description of issue

AutoDMG fails to build a DMG with the new provided full macOS Catalina App installer 10.15.4 19E224g

## Expected behavior

Get a final osx-10.15.4-19E224g.apfs.dmg

## Actual behavior

AutoDMG fails after creating the APFS volume for installation with error:

## Steps to reproduce

1. Download Install macOS Catalina Beta via App Store
2. Download latest AutoDMG app
3. Start AutoDMG and drag Catalina Beta 
4. Push Build and save
5. AutoDMG starts installation and fails with error after a few seconds

Let me know if this is an macOS issue. I can file an Apple Care ticket.

## Log file

[AutoDMG 2020-02-07 15.21.log](https://github.com/MagerValp/AutoDMG/files/4171294/AutoDMG.2020-02-07.15.21.log)

**Comment by MagerValp** [comment]
Looks like a broken installer:

`Couldn't mount the payload dmg ((null)): Error Domain=com.apple.osinstall Code=-34 "An error occurred while loading the installer resources."`

**Comment by sebFischer** [comment]
Tack Per, looks like another download shows the same issue. Will wait for another build.

**Comment by MagerValp** [comment]
My bad, someone pointed out in the log that:

    Setting source path to '/Applications/Install macOS Catalina Beta.app'

See: https://github.com/MagerValp/AutoDMG/wiki/FAQ#0-where-should-i-put-the-install-macos-app-so-that-autodmg-can-use-it

**Comment by sebFischer** [comment]
Thanks again Per, i forget about that! Could now create successful an image.
