### ISSUE TITLE
Fails to build dmg with Catalina 101.15.4 19E2269

### ISSUE THREAD

**Issue by 1dontc0de** [MagerValp/AutoDMG#249]
## Description of issue
Fails to build dmg.

foo

## Expected behavior
Successfully build dmg
bar

## Actual behavior
Error initializing an OS installation.  Verify /Volumes/data/Software/7 - Mac/macOS/10.15/Install macOS Catalina.app/Contents/SharedSupport/InstallInfo.plist exists and is a valid package or collection.
2020-05-11 08:32:42 Error: Workflow failed: Build failed (Installation of 'InstallInfo.plist' failed with return code 1.
Task exited status 102
baz

## Steps to reproduce

1. Build using latest MacOS Catalina installer on bare metal Mac with Catalina or a VM with Catalina 10.15.4
2. build with or without updates
3. fails with errors

## Log file
[AutoDMG 2020-05-11 08.33.log](https://github.com/MagerValp/AutoDMG/files/4611042/AutoDMG.2020-05-11.08.33.log)

_(Save the debug log and attach it by dragging it here)_

**Comment by MagerValp** [comment]
Apple's installer failed. Bad installer app maybe?

`2020-05-11 08:32:42 Info: installer.Error:  Couldn't mount the payload dmg ((null)): Error Domain=com.apple.osinstall Code=-34 "An error occurred while loading the installer resources." UserInfo={NSLocalizedDescription=An error occurred while loading the installer resources.}`

**Comment by 1dontc0de** [comment]
Tried 3 different Macs and downloaded the installer once more from Apple, no dice.  I've even disabled our EPP in case it was being blocked.  Any other suggestions?

**Comment by 1dontc0de** [comment]
Hi my colleague assisted me with this.

Tried installing manually using the instructions here:

https://github.com/MagerValp/AutoDMG/wiki/How-Does-AutoDMG-Work

The installer command fails with the error above.  Steps to reproduce:

root@sn ~ # hdiutil attach -noverify -mountpoint /tmp/installesd /Applications/Install\ macOS\ Catalina.app/Contents/SharedSupport/InstallESD.dmg 
/dev/disk2          	GUID_partition_scheme          	
/dev/disk2s1        	EFI                            	
/dev/disk2s2        	Apple_HFS                      	/private/tmp/installesd
root@sn ~ # hdiutil attach -noverify -mountpoint /tmp/os -owners on /Users/Shared/install.sparseimage 
/dev/disk3          	GUID_partition_scheme          	
/dev/disk3s1        	EFI                            	
/dev/disk3s2        	Apple_HFS                      	/private/tmp/os
root@sn ~ # df -h
Filesystem                                                   Size   Used  Avail Capacity   iused      ifree %iused  Mounted on
/dev/disk1s1                                                233Gi   10Gi  189Gi     6%    487458 2447613862    0%   /
devfs                                                       198Ki  198Ki    0Bi   100%       690          0  100%   /dev
/dev/disk1s5                                                233Gi   32Gi  189Gi    15%    313795 2447787525    0%   /System/Volumes/Data
/dev/disk1s4                                                233Gi  1.0Gi  189Gi     1%         2 2448101318    0%   /private/var/vm
map auto_home                                                 0Bi    0Bi    0Bi   100%         0          0  100%   /System/Volumes/Data/home
map -fstab                                                    0Bi    0Bi    0Bi   100%         0          0  100%   
/dev/disk2s2                                                7.5Gi  7.2Gi  339Mi    96%         8 4294967271    0%   /private/tmp/installesd
/dev/disk3s2                                                 32Gi  7.8Gi   24Gi    25%      1063 4294966216    0%   /private/tmp/os
root@sn ~ # installer -pkg /tmp/installesd/Packages/OSInstall.mpkg -target /tmp/os 
installer: OS Install started.
installer: The OS Install failed with error: Error Domain=com.apple.osinstall Code=-3 "Volume contains a macOS or OS X installation which may be damaged." UserInfo={NSLocalizedDescription=Volume contains a macOS or OS X installation which may be damaged., NSLocalizedFailureReason=Volume contains a macOS or OS X installation which may be damaged.}.


Tried running the Apple USB media creation tool with known good USB stick, and the command succeeded (verifying that the installer should be good):

https://support.apple.com/sl-si/HT201372

Can you confirm that the installer command above is valid?

**Comment by natcable** [comment]
I'm also having trouble running the OSInstall.mpkg directly:

May 12 18:49:22  installer[958] <Error>: OSIInstallElement <OSIInstallRecoverySystemElement: 0x7ff935ed0ef0> errored out: Error Domain=com.apple.osinstall Code=-31 "A file required for installation could not be found." UserInfo={NSLocalizedDescription=A file required for installation could not be found.}

No description of what the file is, or what is expected.

Also verified the download by creating a bootable USB stick.  

Could something have changed in a recent update to the installer from Apple?

**Comment by MagerValp** [comment]
`/Applications/Install\ macOS\ Catalina.app/Contents/SharedSupport/InstallESD.dmg`

Using an installer app on the system drive triggers the bug described in #222 , see [FAQ 0](https://github.com/MagerValp/AutoDMG/wiki/FAQ).

**Comment by 1dontc0de** [comment]
> `/Applications/Install\ macOS\ Catalina.app/Contents/SharedSupport/InstallESD.dmg`
> 
> Using an installer app on the system drive triggers the bug described in #222 , see [FAQ 0](https://github.com/MagerValp/AutoDMG/wiki/FAQ).

Your suggestion worked.   I will check the FAQs next time.  Thank you.
