### ISSUE TITLE
Workflow failed: Build failed (Installation of 'InstallInfo.plist' failed with return code 1. 

### ISSUE THREAD

**Issue by rainieroadie** [MagerValp/AutoDMG#251]
## Description of issue

2020-06-12 10:49:49 Error: Workflow failed: Build failed (Installation of 'InstallInfo.plist' failed with return code 1. See the log for details.)

## Expected behavior

DMG to build

## Actual behavior

Failed early

## Steps to reproduce

1. Open AutoDMG
2. Drag Catalina install version 15.5.02 to AutoDMG
3. Select Build 

## Log file

[AutoDMG 2020-06-12 10.56.log](https://github.com/MagerValp/AutoDMG/files/4772552/AutoDMG.2020-06-12.10.56.log)

**Comment by rainieroadie** [comment]
I followed the steps on this issue without success: https://github.com/MagerValp/AutoDMG/issues/226

**Comment by MagerValp** [comment]
Collecting these as duplicates of #252
