### ISSUE TITLE
Cannot determine default scripting component

### ISSUE THREAD

**Issue by 128keaton** [MagerValp/AutoDMG#253]
## Description of issue

When using an AutoDMG image of 10.15.5, I cannot use any Applescript features once the machine is booted.

Running `osascript` via the CLI results in `osascript can't open default scripting component`

![Screen Shot 2020-06-23 at 11 40 59 AM](https://user-images.githubusercontent.com/1402918/85430948-73998300-b546-11ea-8093-35face885b63.png)

## Expected behavior

The ability to run/use Applescript features

## Actual behavior

No Applescript applet, script, etc works

## Steps to reproduce

1. Use AutoDMG to create a 10.15.5 clean disk image
2. Use AutoCasperNBI to build a NetBoot set or clone the disk image to a drive to boot.
3. Boot from NetBoot set/drive and attempt to use Applescript features.

## Log file

[AutoDMG 2020-06-23 11.39.log](https://github.com/MagerValp/AutoDMG/files/4820703/AutoDMG.2020-06-23.11.39.log)

**Comment by MagerValp** [comment]
Sorry, you'll have to file a bug with Apple, AutoDMG has nothing to do with AppleScript.

**Comment by 128keaton** [comment]
@MagerValp Um. Okay. It only happens with AutoDMG generated images. I can post some more debugging information from `ntruss`. I wouldn't post here if I wasn't sure.
