### ISSUE TITLE
Unable to Build DMG on 10.15.7 with latest AutoDMG release

### ISSUE THREAD

**Issue by 8lu3vegan** [MagerValp/AutoDMG#256]
## Description of issue 

Unable to build DMG

## Expected behavior

Failure with greyed out Build button

## Actual behavior

failure to build DMG 

## Steps to reproduce

1. Download AutoDMG from Github on Catalina 10.15.7
2. double click to open and accept
3. Error automatically pops up 

## Log file

_(Save the debug log and attach it by dragging it here)_

[AutoDMG 2020-11-16 08.55.log](https://github.com/MagerValp/AutoDMG/files/5546690/AutoDMG.2020-11-16.08.55.log)
[AutoDMG 2020-11-16 08.55.log](https://github.com/MagerValp/AutoDMG/files/5546700/AutoDMG.2020-11-16.08.55.log)

**Comment by MagerValp** [comment]
> 2020-11-16 08:54:46 Error: Profile update failed: Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={_kCFStreamErrorCodeKey=-9858, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x600003801530 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSErrorFailingURLStringKey=https://raw.githubusercontent.com/MagerValp/AutoDMGUpdateProfiles/master/UpdateProfiles.plist, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFNetworkCFStreamSSLErrorOriginalValue=-9858, _kCFStreamPropertySSLClientCertificateState=0, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., _kCFStreamErrorDomainKey=3, NSErrorFailingURLKey=https://raw.githubusercontent.com/MagerValp/AutoDMGUpdateProfiles/master/UpdateProfiles.plist, _kCFStreamErrorCodeKey=-9858}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://raw.githubusercontent.com/MagerValp/AutoDMGUpdateProfiles/master/UpdateProfiles.plist, NSErrorFailingURLStringKey=https://raw.githubusercontent.com/MagerValp/AutoDMGUpdateProfiles/master/UpdateProfiles.plist, _kCFStreamErrorDomainKey=3}
