### ISSUE TITLE
Restoring Catalina system image fails

### ISSUE THREAD

**Issue by cardinal701** [MagerValp/AutoDMG#258]
## Description of issue

In the past I have used AutoDMG to create a system image for Mojave, copied it to a USB drive, booted into the built in macOS Recovery Disk Utility, and used the Restore option along with the .dmg created by AutoDMG to install Mojave.  However now I am trying to do the same process for Catalina and it's not working.  I was able to create the system image, however the Restore process isn't working.

## Expected behavior

The restore process installs Catalina on the internal disk.

## Actual behavior

When trying to Restore I see the following message: The disk image "Mac Labs Catalina.dmg" contains more than one APFS volume.  Choose which volume to restore."  The two volumes listed are Macintosh HD, and Macintosh HD-Data. 

I have tried restoring from both and receive the same error messages for both:

Restore process has failed.
Image "/Volumes/Files/Mac Labs Catalina.dmg" doesn't have any appropriate volumes to restore.
Could not validate source - Invalid argument
The operation couldn't be completed. (OSStatus error 22.)

## Steps to reproduce

1. Created system image for Catalina using AutoDMG 1.10b587
2. Copied system image DMG file to external usb drive
3. Started Mac from built in macOS Recovery (Command + R) and launched Disk Utility
4. Erased Internal Drive
5. Selected Internal Drive and chose Restore
6. Selected system image DMG file on usb drive and clicked Restore

## Log file

_(Save the debug log and attach it by dragging it here)_

**Comment by jazzace** [comment]
This is not an issue with AutoDMG. AutoDMG correctly creates the bifurcated boot drive arrangement that was introduced with Catalina. The fact that it is difficult to copy using Disk Utility cannot be fixed with changes to AutoDMG.

**Comment by cardinal701** [comment]
> This is not an issue with AutoDMG. AutoDMG correctly creates the bifurcated boot drive arrangement that was introduced with Catalina. The fact that it is difficult to copy using Disk Utility cannot be fixed with changes to AutoDMG.

Do you know of any other solutions to apply the image created by AutoDMG?

**Comment by jazzace** [comment]
I haven't done it, but I believe `asr` at the command line should work with the right incantation. You may want to search in the MacAdmins Slack or online generally for help with this (and whether this is even a viable workflow based on your context).

**Comment by mpermann** [comment]
@cardinal701 if you use a command similar to the one below from Terminal you should be able to restore the AutoDMG created DMG to the system. 

`sudo asr restore --source /Users/mpermann/Desktop/Base_macOS_10.15.7-19H15.apfs_01-28-2021.dmg --target /dev/disk3 --erase`

Substitute the path to your AutoDMG created base macOS 10.15.7 for the following
`/Users/mpermann/Desktop/Base_macOS_10.15.7-19H15.apfs_01-28-2021.dmg `

Substitute the APFS container disk identifier (typically in your situation it would be /dev/disk1 for the following
`/dev/disk3`

That should allow the restore to happen.
