### ISSUE TITLE
Documentation/Wiki issue re: path to IncludedTemplate?

### ISSUE THREAD

**Issue by arubdesu** [MagerValp/AutoDMG#54]
I got a failure when using an IncludedTemplate, I needed a full path to the template as (I'm guessing) it error'd because the file wasn't in my working directory. Error was `Couldn't read dictionary from plist at`_filename_. The example on https://github.com/MagerValp/AutoDMG/wiki/Templates doesn't show a full path, perhaps that would be good to update or call out specifically in the description of that key.

**Comment by MagerValp** [comment]
After two years of not implementing deterministic relative path handling, I think it's safe to say that it's going to keep being "it depends". Added a note in the wiki.
