### ISSUE TITLE
CLI build fails if not logged into console.

### ISSUE THREAD

**Issue by paulbloch** [MagerValp/AutoDMG#78]
I'm working with AutoDMG 1.4.3 on Mavericks 10.9.4.  If I ssh to my build host and run `AutoDMG build 19.4.4.adtmpl` it fails with

_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
Workflow failed: Build failed (Application isn’t running.)
Build failed: Build failed
    Application isn’t running.

It works fine if I use ARD to login to the console and run it in a console terminal.  When I last used AutoDMG 1.3.2 on OSX 10.8, it worked fine from an ssh terminal.

I can provide more detailed logs or copy of my template as necessary.

**Comment by funroll** [comment]
Just throwing it out there: this might be a good place to use gist.github.com.
