### ISSUE TITLE
Configure location for Application Support files

### ISSUE THREAD

**Issue by ygini** [MagerValp/AutoDMG#83]
It could be interesting to add a global settings to pass to the command line to edit the base folder for Application Support and things like that.

By default it's in the home folder, who can be problematic when run as root.

Such an option can allow us to specify an external volume for example.

**Comment by MagerValp** [comment]
As the support directory is only a couple of hundred megs for most people, and certainly less than a gig, I don't think it's worth implementing mechanism for moving it. Redirecting it with a symbolic link will have to be the officially supported workaround.

**Comment by ygini** [comment]
@MagerValp the problem is linked to the command line version, not the GUI.

When running with command line and templates, you need to run the tool as root, and when doing this the tool try to create some files in the root Application Support who doesn't exist.

I just ask for a settings in the templating system.

**Comment by MagerValp** [comment]
When running on the command line the official recommendation is to [not run as root](https://github.com/MagerValp/AutoDMG/wiki/Command-Line-Interface#a-note-on-sudo), to avoid any issues with updates and profiles. If you do run as root, presumably from a cron or launchd script, you have to run `update` and `download` before `build`, which will create the needed support files.
