### ISSUE TITLE
menu items disappear

### ISSUE THREAD

**Issue by GayleSnail** [MagerValp/AutoDMG#95]
when creating a 10.10.1 image with AutoDMG, the only thing I'm seeing (or lack thereof) are a some of the menu bar items during a clean install. Sound, Wi-Fi, Time machine, BlueTooth.

The DMG was created with a newly downloaded 10.10.1 Installer from the app store using the latest AutoDMG.

tried on a few machines same issue.

**Comment by MagerValp** [comment]
I'm afraid you'll have to be a little more specific as to what the problem is.

**Comment by GayleSnail** [comment]
hi - so when i installed the 10.10.1 autoDMG OS onto a few test machines, after going through the set-up assistant menu bar items are not loading in a new user account.
for example the clock shows up, and spotlight, - but not volume, bluetooth, wifi airport, time machine icons, etc.

**Comment by mwohlgemuth** [comment]
Thats default Yosemite behavior, nothing to do with AutoDMG. Do an internet recovery install and see for yourself. Sound, Bluetooth etc are all missing from the Menu Bar by default on OS 10.10 Yosemite.

**Comment by gregneagle** [comment]
If you want those items there for users, consider creating and installing a configuration profile.
