### ISSUE TITLE
404 error trying to get Safari 7.1 update

### ISSUE THREAD

**Issue by ktappe** [MagerValp/AutoDMG#97]
Perhaps it's just a typo in the update profile, but downloading Safari 7.1 from within AutoDMG fails with a 404 error.

EDIT:  This is with the Mavericks 10.9.5 installer.

**Comment by MagerValp** [comment]
Sounds like you need to pull the latest update profile, the current version is 7.1.2.

**Comment by ktappe** [comment]
I only just downloaded the profile before sending this report. What It contained was 7.1. Not sure what's going on.

**Comment by MagerValp** [comment]
Hmm, sounds like the merge went bad after Apple pulled the 7.1.1 update. Try now.

**Comment by ktappe** [comment]
It works! Thanks!
