### ISSUE TITLE
Lack of update profile or particular update should not halt execution

### ISSUE THREAD

**Issue by ktappe** [MagerValp/AutoDMG#98]
If there is no update list, the command line should still build, just without updates. For example, this happens if the GUI has not been used to obtain updates:

"No update profile for 10.9.5 13F34
(null)"

This should not halt execution; it should simply result in an unpatched OS (with appropriate warning to the user.)

Likewise, the lack of a particular update should not halt it either. For example:

"Can't apply updates, Safari 7.1 for Mavericks is missing from cache"

This also should not halt execution, it should just build with all the updates except the missing one.

**Comment by MagerValp** [comment]
I don't agree. The output image should contain what the user's input specified, failure to apply a requested update is an error condition (and a potential security issue). If you want to build an image without a certain update, uncheck apply updates and manually add the ones you want.

**Comment by ktappe** [comment]
I would love to build it without any updates at all. But there's no option to not include updates from the commandline. Unchecking in the GUI has no effect; the commandline still applies updates and fails if it can't obtain them.

**Comment by MagerValp** [comment]
Running `/Applications/AutoDMG.app/Contents/MacOS/AutoDMG build /Applications/Install\ OS\ X\ 10.10.1\ 14B25/Install\ OS\ X\ Yosemite.app -o yoyo.dmg` (without the `-u` flag) builds an image without updates from the CLI. If you're using a template make sure it has `ApplyUpdates` set to false (or not present).
